import { Router } from 'express';
import { allowRoles, requireAuth } from '../middleware/auth.js';
import { changeJobStatus, createJob, deleteJob, getCompanyProfile, getOverview, getSettings, listApplicants, listJobs, saveCompanyProfile, updateApplicationStatus, updateJob, updateSettings } from '../controllers/recruiterController.js';
import { getNotifications, readAllNotifications, readNotification, searchCandidates } from '../controllers/recruiterDiscoveryController.js';
import { addCandidateToPool, createTalentPool, deleteTalentPool, listRecruiterInterviews, listTalentPools, removeCandidateFromPool, scheduleInterview, updateInterview } from '../controllers/recruiterGrowthController.js';
import { listConversations, listMessages, sendMessage, startApplicationConversation, startConversation } from '../controllers/messagingController.js';
const router=Router();
router.use(requireAuth,allowRoles('recruiter'));
router.get('/overview',getOverview);
router.get('/company',getCompanyProfile);
router.put('/company',saveCompanyProfile);
router.get('/jobs',listJobs);
router.post('/jobs',createJob);
router.put('/jobs/:id',updateJob);
router.patch('/jobs/:id/status',changeJobStatus);
router.delete('/jobs/:id',deleteJob);
router.get('/applicants',listApplicants);
router.patch('/applications/:id/status',updateApplicationStatus);
router.post('/applications/:applicationId/conversation',startApplicationConversation);
router.get('/candidates/search',searchCandidates);
router.get('/talent-pools',listTalentPools);
router.post('/talent-pools',createTalentPool);
router.delete('/talent-pools/:id',deleteTalentPool);
router.put('/talent-pools/:id/candidates',addCandidateToPool);
router.delete('/talent-pools/:id/candidates/:candidateId',removeCandidateFromPool);
router.get('/interviews',listRecruiterInterviews);
router.post('/interviews',scheduleInterview);
router.patch('/interviews/:id',updateInterview);
router.get('/messages',listConversations);
router.post('/messages',startConversation);
router.get('/messages/:id',listMessages);
router.post('/messages/:id',sendMessage);
router.get('/notifications',getNotifications);
router.patch('/notifications/read-all',readAllNotifications);
router.patch('/notifications/:id/read',readNotification);
router.get('/settings',getSettings);
router.patch('/settings',updateSettings);
export default router;
