import mongoose from 'mongoose';
import AdminActivity from '../models/AdminActivity.js';
import Company from '../models/Company.js';
import Job from '../models/Job.js';
import User from '../models/User.js';
import { brandedEmail,sendEmail } from '../services/emailService.js';
import { notifyMatchingJobAlerts } from '../services/notificationService.js';

const userStatuses=new Set(['pending','active','suspended']);
const companyStatuses=new Set(['pending','verified','rejected']);
const jobStatuses=new Set(['draft','published','reviewing','paused','closed']);
const validId=(value)=>mongoose.isValidObjectId(value);
async function log(req,action,entityType,entityId,description,metadata={}){try{await AdminActivity.create({admin:req.user._id,action,entityType,entityId:String(entityId||''),description,metadata});}catch(error){console.error('Admin audit log failed:',error.message);}}
async function pauseRecruiterJobs(recruiterId){return Job.updateMany({createdBy:recruiterId,status:'published'},{$set:{status:'paused'}});}
async function setRecruiterStatus(req,res,recruiter,status){if(recruiter.status===status)return res.status(409).json({message:`Recruiter account is already ${status}.`});if(status==='active'&&!recruiter.emailVerified)return res.status(409).json({message:'Recruiter must verify their email before the account can be approved.'});const previousStatus=recruiter.status;recruiter.status=status;await recruiter.save({validateBeforeSave:false});if(status!=='active')await pauseRecruiterJobs(recruiter._id);await log(req,'recruiter.status','User',recruiter._id,`Recruiter ${recruiter.email} changed from ${previousStatus} to ${status}.`,{previousStatus,status});if(status==='active'&&previousStatus!=='active'){const loginUrl=`${process.env.CLIENT_URL}/login`;try{await sendEmail({to:recruiter.email,subject:'Your RB Service Connect recruiter account is approved',html:brandedEmail({eyebrow:'Recruiter access',title:'Your recruiter account is approved',greeting:`Hello ${recruiter.firstName},`,paragraphs:['Your Royalties Service Connect recruiter account has been reviewed and approved.','You can now sign in to your recruiter workspace and continue setting up your employer profile and hiring activity.'],buttonLabel:'Open recruiter workspace',buttonUrl:loginUrl,note:'If you were not expecting this approval, contact the RB Service Connect team through the website.'}),text:`Hello ${recruiter.firstName},\n\nYour Royalties Service Connect recruiter account has been approved.\n\nSign in: ${loginUrl}`});}catch(error){console.error('Recruiter approval email failed:',error.message);}}return res.json({message:status==='active'?'Recruiter approved successfully':`Recruiter status changed to ${status}`,recruiter:{id:recruiter._id,firstName:recruiter.firstName,lastName:recruiter.lastName,email:recruiter.email,status:recruiter.status,updatedAt:recruiter.updatedAt}});}

export async function updateUserStatus(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid user reference.'});const status=String(req.body.status||'');if(!userStatuses.has(status))return res.status(400).json({message:'Invalid account status.'});const user=await User.findById(req.params.id);if(!user)return res.status(404).json({message:'User not found.'});if(String(user._id)===String(req.user._id))return res.status(400).json({message:'You cannot change your own admin status.'});if(user.role==='admin')return res.status(403).json({message:'Admin account status cannot be changed from user management.'});if(user.role==='recruiter')return setRecruiterStatus(req,res,user,status);if(user.status===status)return res.status(409).json({message:`User account is already ${status}.`});const previousStatus=user.status;user.status=status;await user.save({validateBeforeSave:false});await log(req,'user.status','User',user._id,`Changed ${user.email} from ${previousStatus} to ${status}.`,{role:user.role,previousStatus,status});return res.json({message:'User status updated.',user:{id:user._id,status:user.status}});}
export async function updateRecruiterStatus(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid recruiter reference.'});const status=String(req.body.status||'');if(!userStatuses.has(status))return res.status(400).json({message:'Invalid recruiter status.'});const recruiter=await User.findOne({_id:req.params.id,role:'recruiter'});if(!recruiter)return res.status(404).json({message:'Recruiter account not found.'});return setRecruiterStatus(req,res,recruiter,status);}
export async function updateCompanyStatus(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid company reference.'});const status=String(req.body.status||'');if(!companyStatuses.has(status))return res.status(400).json({message:'Invalid company verification status.'});const company=await Company.findById(req.params.id).populate('owner','role status emailVerified');if(!company)return res.status(404).json({message:'Company not found.'});if(company.verificationStatus===status)return res.status(409).json({message:`Company is already ${status}.`});if(status==='verified'&&(!company.owner||company.owner.role!=='recruiter'||company.owner.status!=='active'||!company.owner.emailVerified))return res.status(409).json({message:'Company can only be verified for an active, email-verified recruiter account.'});const previousStatus=company.verificationStatus;company.verificationStatus=status;await company.save();if(status!=='verified')await Job.updateMany({company:company._id,status:'published'},{$set:{status:'paused'}});await log(req,'company.verification','Company',company._id,`Company ${company.name} changed from ${previousStatus} to ${status}.`,{previousStatus,status});return res.json({message:'Company verification updated.',company:{id:company._id,verificationStatus:company.verificationStatus}});}
export async function updateJobStatus(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid job reference.'});const status=String(req.body.status||'');if(!jobStatuses.has(status))return res.status(400).json({message:'Invalid job status.'});const job=await Job.findById(req.params.id).populate('company','verificationStatus').populate('createdBy','role status emailVerified');if(!job)return res.status(404).json({message:'Job not found.'});if(job.status===status)return res.status(409).json({message:`Job is already ${status}.`});if(status==='published'){if(!job.company||job.company.verificationStatus!=='verified')return res.status(409).json({message:'A job can only be published for a verified company.'});if(!job.createdBy||job.createdBy.role!=='recruiter'||job.createdBy.status!=='active'||!job.createdBy.emailVerified)return res.status(409).json({message:'A job can only be published for an active, verified recruiter account.'});if(job.applicationDeadline&&job.applicationDeadline<=new Date())return res.status(409).json({message:'Set a future application deadline before publishing this job.'});}const previousStatus=job.status;job.status=status;if(status==='published'&&!job.publishedAt)job.publishedAt=new Date();job.closedAt=status==='closed'?new Date():null;await job.save();await log(req,'job.status','Job',job._id,`Job ${job.title} changed from ${previousStatus} to ${status}.`,{previousStatus,status});if(status==='published'&&previousStatus!=='published')notifyMatchingJobAlerts(job).catch((error)=>console.error('Job alert matching after admin publish failed:',error.message));return res.json({message:'Job status updated.',job:{id:job._id,status:job.status}});}
