import mongoose from 'mongoose';
import CareerEnrollment from '../models/CareerEnrollment.js';
import User from '../models/User.js';
import { createNotification } from '../services/notificationService.js';

const serviceKeys=['resumeReview','profileOptimization','curatedMatching','interviewPrep','mockInterview','recruiterIntroductions','salaryNegotiation','advisorSupport'];
const statuses=['active','placed','completed','withdrawn','cancelled'];
const transitions={active:new Set(['placed','completed','withdrawn','cancelled']),placed:new Set(['completed','cancelled']),completed:new Set(),withdrawn:new Set(),cancelled:new Set()};
const pageInfo=(req)=>{const page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));return{page,limit,skip:(page-1)*limit};};
const safeRegex=(value='')=>String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
export async function listCareerEnrollments(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(statuses.includes(req.query.status))filter.status=req.query.status;if(req.query.program)filter.program=String(req.query.program).trim().slice(0,60);if(req.query.q){const q=String(req.query.q).trim().slice(0,120),rx=new RegExp(safeRegex(q),'i');const users=await User.find({role:'candidate',$or:[{firstName:rx},{lastName:rx},{email:rx}]}).select('_id').lean();filter.candidate={$in:users.map((u)=>u._id)};}const [enrollments,total,summary]=await Promise.all([CareerEnrollment.find(filter).populate('candidate','firstName lastName email status').populate({path:'placedApplication',select:'status job',populate:{path:'job',select:'title company',populate:{path:'company',select:'name'}}}).sort({createdAt:-1}).skip(skip).limit(limit).lean(),CareerEnrollment.countDocuments(filter),CareerEnrollment.aggregate([{$group:{_id:'$status',count:{$sum:1},fees:{$sum:'$successFeeAmount'}}}])]);return res.json({enrollments,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1},summary});}
export async function updateCareerEnrollment(req,res){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid career programme reference.'});const enrollment=await CareerEnrollment.findById(req.params.id);if(!enrollment)return res.status(404).json({message:'Career programme enrollment not found.'});let changed=false;if(req.body.status!==undefined){if(!statuses.includes(req.body.status))return res.status(400).json({message:'Invalid programme status.'});if(req.body.status===enrollment.status)return res.status(409).json({message:`Programme is already ${enrollment.status}.`});if(!transitions[enrollment.status]?.has(req.body.status))return res.status(409).json({message:`Programme cannot move from ${enrollment.status} to ${req.body.status}.`});if(req.body.status==='placed'&&!enrollment.placedApplication)return res.status(409).json({message:'A programme cannot be marked placed until a verified placement is linked.'});enrollment.status=req.body.status;changed=true;}if(req.body.service!==undefined||req.body.completed!==undefined){if(!serviceKeys.includes(req.body.service)||typeof req.body.completed!=='boolean')return res.status(400).json({message:'A valid career service and completion state are required.'});if(['completed','withdrawn','cancelled'].includes(enrollment.status))return res.status(409).json({message:'Services cannot be changed after the programme has ended.'});if(enrollment.services?.[req.body.service]===req.body.completed)return res.status(409).json({message:'Career service already has that completion state.'});enrollment.services[req.body.service]=req.body.completed;enrollment.markModified('services');changed=true;}if(!changed)return res.status(400).json({message:'Choose a programme status or service update.'});await enrollment.save();await createNotification({user:enrollment.candidate,type:'career_program',title:'Career programme updated',message:req.body.status!==undefined?`Your career programme status is now ${enrollment.status}.`:'A service milestone in your career programme was updated.',link:'/candidate/career-programs',metadata:{careerEnrollmentId:enrollment._id}});return res.json({message:'Career programme updated.',enrollment});}
