import SuccessFee from '../models/SuccessFee.js';
import { createNotification } from '../services/notificationService.js';

const terminalStatuses=['paid','waived','cancelled'];
const safeText=(value,max=1000)=>String(value||'').trim().slice(0,max);
const positiveMoney=(value)=>{const amount=Math.round(Number(value)||0);return amount>0?amount:0;};
const validDate=(value)=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};
const pageInfo=(req)=>{const page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));return{page,limit,skip:(page-1)*limit};};
const populate=(query)=>query.populate('candidate','firstName lastName email').populate('recruiter','firstName lastName email').populate('company','name').populate('job','title slug').populate('application','status createdAt');

export async function listPlacements(req,res){const {page,limit,skip}=pageInfo(req);const filter={};const allowed=['awaiting_hire_confirmation','awaiting_candidate_confirmation','awaiting_first_salary','payment_due','paid','disputed','waived','cancelled'];if(allowed.includes(req.query.status))filter.status=req.query.status;const [placements,total,summary]=await Promise.all([populate(SuccessFee.find(filter)).sort({createdAt:-1}).skip(skip).limit(limit).lean(),SuccessFee.countDocuments(filter),SuccessFee.aggregate([{$group:{_id:'$status',count:{$sum:1},fees:{$sum:'$feeAmount'}}}])]);return res.json({placements,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1},summary});}

export async function resolvePlacement(req,res){const fee=await SuccessFee.findById(req.params.id);if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(terminalStatuses.includes(fee.status))return res.status(400).json({message:'A completed, waived, or cancelled placement cannot be resolved again.'});const salaryAmount=positiveMoney(req.body.salaryAmount);const startDate=validDate(req.body.startDate);const resolution=safeText(req.body.resolution);if(!salaryAmount||!startDate||!resolution)return res.status(400).json({message:'Verified salary, joining date, and resolution note are required.'});fee.recruiterConfirmation={confirmed:true,salaryAmount,startDate,confirmedAt:fee.recruiterConfirmation?.confirmedAt||new Date()};fee.candidateConfirmation={confirmed:true,salaryAmount,startDate,confirmedAt:fee.candidateConfirmation?.confirmedAt||new Date()};fee.firstSalaryAmount=salaryAmount;fee.dispute={...fee.dispute?.toObject?.()||fee.dispute,reason:fee.dispute?.reason||'Placement details required administrator review.',openedBy:fee.dispute?.openedBy||req.user._id,openedAt:fee.dispute?.openedAt||new Date(),resolvedAt:new Date(),resolution};fee.status=fee.firstSalary?.received?'payment_due':'awaiting_first_salary';await fee.save();await Promise.all([createNotification({user:fee.candidate,type:'placement_confirmation',title:'Placement review resolved',message:'RB Service Connect reviewed and reconciled your placement details.',link:'/candidate/placements',metadata:{successFeeId:fee._id}}),createNotification({user:fee.recruiter,type:'placement_confirmation',title:'Placement review resolved',message:'RB Service Connect reviewed and reconciled the placement details.',link:'/recruiter/placements',metadata:{successFeeId:fee._id}})]);return res.json({message:'Placement dispute resolved and verified details recorded.',placement:await populate(SuccessFee.findById(fee._id)).lean()});}

export async function waivePlacement(req,res){const fee=await SuccessFee.findById(req.params.id);if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(fee.status==='paid')return res.status(400).json({message:'A paid placement cannot be waived.'});const resolution=safeText(req.body.resolution);if(!resolution)return res.status(400).json({message:'A waiver reason is required.'});fee.status='waived';fee.dispute={...fee.dispute?.toObject?.()||fee.dispute,resolvedAt:new Date(),resolution:`Fee waived: ${resolution}`};await fee.save();await createNotification({user:fee.candidate,type:'placement_confirmation',title:'Career programme fee waived',message:'RB Service Connect has waived the fee associated with this verified placement.',link:'/candidate/placements',metadata:{successFeeId:fee._id}});return res.json({message:'Placement fee waived.'});}

export async function cancelPlacement(req,res){const fee=await SuccessFee.findById(req.params.id);if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(fee.status==='paid')return res.status(400).json({message:'A paid placement cannot be cancelled.'});const resolution=safeText(req.body.resolution);if(!resolution)return res.status(400).json({message:'A cancellation reason is required.'});fee.status='cancelled';fee.dispute={...fee.dispute?.toObject?.()||fee.dispute,resolvedAt:new Date(),resolution:`Placement cancelled: ${resolution}`};await fee.save();await Promise.all([createNotification({user:fee.candidate,type:'placement_confirmation',title:'Placement verification closed',message:'RB Service Connect closed this placement verification record.',link:'/candidate/placements',metadata:{successFeeId:fee._id}}),createNotification({user:fee.recruiter,type:'placement_confirmation',title:'Placement verification closed',message:'RB Service Connect closed this placement verification record.',link:'/recruiter/placements',metadata:{successFeeId:fee._id}})]);return res.json({message:'Placement verification cancelled.'});}
