import mongoose from 'mongoose';
import AdminActivity from '../models/AdminActivity.js';
import Application from '../models/Application.js';
import Company from '../models/Company.js';
import ContactMessage from '../models/ContactMessage.js';
import Job from '../models/Job.js';
import PlatformSettings from '../models/PlatformSettings.js';
import Promotion from '../models/Promotion.js';
import User from '../models/User.js';

const userStatuses=['pending','active','suspended'];const recruiterStatuses=['pending','active','suspended'];const companyStatuses=['pending','verified','rejected'];const jobStatuses=['draft','published','reviewing','paused','closed'];const contactStatuses=['new','reviewed','resolved'];const promotionStatuses=['pending','active','expired','cancelled'];
const safeRegex=(value='')=>String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const pageInfo=(req)=>{const page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));return{page,limit,skip:(page-1)*limit};};const validId=(value)=>mongoose.isValidObjectId(value);const bounded=(value,max)=>String(value||'').trim().slice(0,max);
async function log(req,action,entityType,entityId,description,metadata={}){try{await AdminActivity.create({admin:req.user._id,action,entityType,entityId:String(entityId||''),description,metadata});}catch(error){console.error('Admin audit log failed:',error.message);}}async function settings(){return PlatformSettings.findOneAndUpdate({key:'default'},{$setOnInsert:{key:'default'}},{new:true,upsert:true,setDefaultsOnInsert:true});}
export async function getDashboard(_req,res){const [users,candidates,recruiters,pendingRecruiters,companies,publishedJobs,reviewingJobs,applications,hires,newContacts,recentUsers,recentApps,recentActivity]=await Promise.all([User.countDocuments(),User.countDocuments({role:'candidate'}),User.countDocuments({role:'recruiter'}),User.countDocuments({role:'recruiter',status:'pending'}),Company.countDocuments(),Job.countDocuments({status:'published'}),Job.countDocuments({status:'reviewing'}),Application.countDocuments(),Application.countDocuments({status:'hired'}),ContactMessage.countDocuments({status:'new'}),User.find().select('firstName lastName email role status createdAt').sort({createdAt:-1}).limit(5).lean(),Application.find().sort({createdAt:-1}).limit(5).populate('candidate','firstName lastName email').lean(),AdminActivity.find().sort({createdAt:-1}).limit(8).populate('admin','firstName lastName email').lean()]);return res.json({counts:{users,candidates,recruiters,pendingRecruiters,companies,publishedJobs,reviewingJobs,applications,hires,newContacts},recentUsers,recentApplications:recentApps,recentActivity});}
export async function listUsers(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.role&&['candidate','recruiter','admin'].includes(req.query.role))filter.role=req.query.role;if(req.query.status&&userStatuses.includes(req.query.status))filter.status=req.query.status;if(req.query.q){const rx=new RegExp(safeRegex(bounded(req.query.q,120)),'i');filter.$or=[{firstName:rx},{lastName:rx},{email:rx}];}const [items,total]=await Promise.all([User.find(filter).select('firstName lastName email role status emailVerified lastLoginAt createdAt updatedAt').sort({createdAt:-1}).skip(skip).limit(limit).lean(),User.countDocuments(filter)]);return res.json({users:items,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function listRecruiters(req,res){const filter={role:'recruiter'};if(req.query.status&&recruiterStatuses.includes(req.query.status))filter.status=req.query.status;const recruiters=await User.find(filter).select('firstName lastName email role status emailVerified createdAt updatedAt lastLoginAt').sort({createdAt:-1}).lean();return res.json({recruiters});}
export async function listCompanies(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.status&&companyStatuses.includes(req.query.status))filter.verificationStatus=req.query.status;if(req.query.q)filter.name=new RegExp(safeRegex(bounded(req.query.q,120)),'i');const [companies,total]=await Promise.all([Company.find(filter).populate('owner','firstName lastName email status').sort({createdAt:-1}).skip(skip).limit(limit).lean(),Company.countDocuments(filter)]);const ids=companies.map(c=>c._id);const counts=await Job.aggregate([{$match:{company:{$in:ids}}},{$group:{_id:'$company',count:{$sum:1}}}]);const map=new Map(counts.map(x=>[String(x._id),x.count]));return res.json({companies:companies.map(c=>({...c,jobCount:map.get(String(c._id))||0})),pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function listJobs(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.status&&jobStatuses.includes(req.query.status))filter.status=req.query.status;if(req.query.q)filter.title=new RegExp(safeRegex(bounded(req.query.q,120)),'i');const [jobs,total]=await Promise.all([Job.find(filter).populate('company','name slug verificationStatus').populate('createdBy','firstName lastName email status').sort({createdAt:-1}).skip(skip).limit(limit).lean(),Job.countDocuments(filter)]);const ids=jobs.map(j=>j._id);const counts=await Application.aggregate([{$match:{job:{$in:ids}}},{$group:{_id:'$job',count:{$sum:1}}}]);const map=new Map(counts.map(x=>[String(x._id),x.count]));return res.json({jobs:jobs.map(j=>({...j,applicants:map.get(String(j._id))||0})),pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function listApplications(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.status)filter.status=bounded(req.query.status,40);const [applications,total]=await Promise.all([Application.find(filter).populate('candidate','firstName lastName email status').populate({path:'job',select:'title slug status company',populate:{path:'company',select:'name slug'}}).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Application.countDocuments(filter)]);return res.json({applications,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function listContacts(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.status&&contactStatuses.includes(req.query.status))filter.status=req.query.status;if(req.query.q){const rx=new RegExp(safeRegex(bounded(req.query.q,120)),'i');filter.$or=[{name:rx},{email:rx},{message:rx}];}const [contacts,total]=await Promise.all([ContactMessage.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),ContactMessage.countDocuments(filter)]);return res.json({contacts,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function updateContactStatus(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid enquiry reference.'});const status=req.body.status;if(!contactStatuses.includes(status))return res.status(400).json({message:'Invalid enquiry status.'});const contact=await ContactMessage.findById(req.params.id);if(!contact)return res.status(404).json({message:'Enquiry not found.'});if(contact.status===status)return res.status(409).json({message:`Enquiry is already ${status}.`});if(contact.status==='resolved'&&status!=='resolved')return res.status(409).json({message:'A resolved enquiry cannot be reopened through this action.'});contact.status=status;await contact.save();await log(req,'contact.status','ContactMessage',contact._id,`Contact enquiry from ${contact.email} changed to ${status}.`,{status});return res.json({message:'Enquiry updated.',contact});}
export async function deleteContact(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid enquiry reference.'});const contact=await ContactMessage.findByIdAndDelete(req.params.id);if(!contact)return res.status(404).json({message:'Enquiry not found.'});await log(req,'contact.delete','ContactMessage',contact._id,`Deleted contact enquiry from ${contact.email}.`);return res.json({message:'Enquiry deleted.'});}
export async function getAnalytics(_req,res){const [usersByRole,applicationsByStatus,jobsByStatus,registrations]=await Promise.all([User.aggregate([{$group:{_id:'$role',count:{$sum:1}}}]),Application.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),Job.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),User.aggregate([{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$createdAt'}},count:{$sum:1}}},{$sort:{_id:1}},{$limit:12}])]);return res.json({usersByRole,applicationsByStatus,jobsByStatus,registrations});}
export async function getPromotionManagement(req,res){const {page,limit,skip}=pageInfo(req);const filter={};if(req.query.status&&promotionStatuses.includes(req.query.status))filter.status=req.query.status;if(['candidate','recruiter'].includes(req.query.audience))filter.audience=req.query.audience;if(req.query.product)filter.product=bounded(req.query.product,80);const now=new Date();await Promotion.updateMany({status:'active',endsAt:{$lte:now}},{$set:{status:'expired'}});const [promotions,total,summary]=await Promise.all([Promotion.find(filter).populate('owner','firstName lastName email role status').sort({createdAt:-1}).skip(skip).limit(limit).lean(),Promotion.countDocuments(filter),Promotion.aggregate([{$facet:{statuses:[{$group:{_id:'$status',count:{$sum:1},amount:{$sum:'$amount'}}}],paid:[{$match:{'payment.paidAt':{$ne:null}}},{$group:{_id:null,revenue:{$sum:'$amount'},transactions:{$sum:1}}}],products:[{$match:{'payment.paidAt':{$ne:null}}},{$group:{_id:'$product',revenue:{$sum:'$amount'},transactions:{$sum:1}}},{$sort:{revenue:-1}}]}}])]);return res.json({promotions,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1},summary:{statuses:summary[0]?.statuses||[],revenue:summary[0]?.paid?.[0]?.revenue||0,paidTransactions:summary[0]?.paid?.[0]?.transactions||0,products:summary[0]?.products||[]}});}
export async function cancelPromotion(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid promotion reference.'});const promotion=await Promotion.findById(req.params.id);if(!promotion)return res.status(404).json({message:'Promotion not found.'});if(!['pending','active'].includes(promotion.status))return res.status(409).json({message:`A ${promotion.status} promotion cannot be cancelled.`});const previousStatus=promotion.status;promotion.status='cancelled';promotion.endsAt=promotion.endsAt||new Date();await promotion.save();await log(req,'promotion.cancel','Promotion',promotion._id,`Cancelled ${promotion.product} promotion.`,{previousStatus,owner:String(promotion.owner),paymentId:promotion.payment?.paymentId||''});return res.json({message:'Promotion cancelled. This does not issue a Razorpay refund.',promotion:{id:promotion._id,status:promotion.status}});}
export async function listActivity(req,res){const {page,limit,skip}=pageInfo(req);const [activity,total]=await Promise.all([AdminActivity.find().populate('admin','firstName lastName email').sort({createdAt:-1}).skip(skip).limit(limit).lean(),AdminActivity.countDocuments()]);return res.json({activity,pagination:{page,limit,total,pages:Math.ceil(total/limit)||1}});}
export async function getSettings(_req,res){return res.json({settings:await settings()});}
export async function updateSettings(req,res){const current=await settings();const allowed=new Set(['recruiterRegistrationOpen','candidateRegistrationOpen','requireRecruiterApproval','maintenanceMode','supportMessage']);const supplied=Object.keys(req.body||{});if(supplied.some((key)=>!allowed.has(key)))return res.status(400).json({message:'One or more platform settings are not editable.'});let changed=false;for(const key of ['recruiterRegistrationOpen','candidateRegistrationOpen','requireRecruiterApproval','maintenanceMode'])if(typeof req.body[key]==='boolean'&&current[key]!==req.body[key]){current[key]=req.body[key];changed=true;}if(req.body.supportMessage!==undefined){if(typeof req.body.supportMessage!=='string')return res.status(400).json({message:'Support message must be text.'});const value=req.body.supportMessage.trim();if(value.length>300)return res.status(400).json({message:'Support message must be 300 characters or fewer.'});if(current.supportMessage!==value){current.supportMessage=value;changed=true;}}if(!changed)return res.status(409).json({message:'No platform settings changed.'});await current.save();await log(req,'platform.settings','PlatformSettings',current._id,'Updated platform settings.',{fields:supplied});return res.json({message:'Platform settings updated.',settings:current});}
