import crypto from 'node:crypto';
import PlatformSettings from '../models/PlatformSettings.js';
import User from '../models/User.js';
import { brandedEmail, sendEmail } from '../services/emailService.js';
import { clean,validEmail,validPassword,validationError } from '../utils/validation.js';
import { clearAuthCookie, setAuthCookie, signAccessToken } from '../utils/tokens.js';

const tokenHash=(token)=>crypto.createHash('sha256').update(token).digest('hex');
const genericVerification={message:'If an unverified account exists for that email, a new verification link has been sent.'};
const genericReset={message:'If an account exists for that email, a password reset link has been sent.'};
async function issueVerification(user){const token=crypto.randomBytes(32).toString('hex');user.emailVerificationTokenHash=tokenHash(token);user.emailVerificationExpiresAt=new Date(Date.now()+24*60*60*1000);await user.save({validateBeforeSave:false});const verifyUrl=`${process.env.CLIENT_URL}/verify-email?token=${encodeURIComponent(token)}`;const html=brandedEmail({eyebrow:'Account verification',title:'Verify your email address',greeting:`Hello ${user.firstName},`,paragraphs:['Thanks for creating your Royalties Service Connect account.','Verify your email address to activate secure account access. This link expires in 24 hours.'],buttonLabel:'Verify email',buttonUrl:verifyUrl,note:'If you did not create this account, you can ignore this email.'});const text=`Hello ${user.firstName},\n\nVerify your RB Service Connect email address: ${verifyUrl}\n\nThis link expires in 24 hours.`;try{const result=await sendEmail({to:user.email,subject:'Verify your RB Service Connect email',html,text});if(result.skipped&&process.env.NODE_ENV!=='production')console.info(`Email verification link for ${user.email}: ${verifyUrl}`);return verifyUrl;}catch(error){user.emailVerificationTokenHash=null;user.emailVerificationExpiresAt=null;await user.save({validateBeforeSave:false});throw error;}}

export async function register(req,res){
  const firstName=clean(req.body?.firstName,60),lastName=clean(req.body?.lastName,60),email=clean(req.body?.email,254).toLowerCase(),password=String(req.body?.password||''),role=clean(req.body?.role,20)||'candidate';const errors={};
  if(firstName.length<2)errors.firstName='First name must be at least 2 characters.';
  if(lastName.length<2)errors.lastName='Last name must be at least 2 characters.';
  if(!validEmail(email))errors.email='Enter a valid email address.';
  if(!['candidate','recruiter'].includes(role))errors.role='Choose a valid account role.';
  if(!validPassword(password))errors.password='Password must be 8–128 characters and include at least one letter and one number.';
  if(Object.keys(errors).length)return validationError(res,errors);
  const platform=await PlatformSettings.findOne({key:'default'}).lean();if(role==='candidate'&&platform?.candidateRegistrationOpen===false)return res.status(403).json({message:'Candidate registration is temporarily closed.'});if(role==='recruiter'&&platform?.recruiterRegistrationOpen===false)return res.status(403).json({message:'Recruiter registration is temporarily closed.'});
  const existing=await User.exists({email});if(existing)return res.status(409).json({message:'An account with this email already exists',errors:{email:'An account with this email already exists.'}});
  const approvalRequired=platform?.requireRecruiterApproval!==false,status=role==='recruiter'&&approvalRequired?'pending':'active';
  try{const user=await User.create({firstName,lastName,email,password,role,status,emailVerified:false});try{await issueVerification(user);}catch(error){console.error('Verification email failed:',error.message);}return res.status(201).json({message:role==='recruiter'&&approvalRequired?'Recruiter account created. Verify your email, then wait for admin approval.':'Account created. Check your email to verify your account.',requiresEmailVerification:true,user:{id:user._id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role,status:user.status,emailVerified:user.emailVerified}});}catch(error){if(error?.code===11000)return res.status(409).json({message:'An account with this email already exists',errors:{email:'An account with this email already exists.'}});throw error;}
}

export async function verifyEmail(req,res){const token=String(req.body?.token||'');if(!/^[a-f\d]{64}$/i.test(token))return res.status(400).json({message:'This verification link is invalid or has expired.'});const user=await User.findOne({emailVerificationTokenHash:tokenHash(token),emailVerificationExpiresAt:{$gt:new Date()},emailVerified:false}).select('+emailVerificationTokenHash +emailVerificationExpiresAt');if(!user)return res.status(400).json({message:'This verification link is invalid or has expired.'});user.emailVerified=true;user.emailVerificationTokenHash=null;user.emailVerificationExpiresAt=null;await user.save({validateBeforeSave:false});return res.json({message:user.role==='recruiter'&&user.status==='pending'?'Email verified. Your recruiter account is now awaiting admin approval.':'Email verified successfully. You can now sign in.'});}
export async function resendVerification(req,res){const email=clean(req.body?.email,254).toLowerCase();if(!validEmail(email))return res.json(genericVerification);const user=await User.findOne({email,emailVerified:false,status:{$ne:'suspended'}}).select('+emailVerificationTokenHash +emailVerificationExpiresAt');if(!user)return res.json(genericVerification);if(user.emailVerificationExpiresAt&&user.emailVerificationExpiresAt>new Date(Date.now()+23*60*60*1000))return res.json(genericVerification);try{await issueVerification(user);}catch(error){console.error('Verification resend failed:',error.message);}return res.json(genericVerification);}

export async function login(req,res){const email=clean(req.body?.email,254).toLowerCase(),password=String(req.body?.password||'');const errors={};if(!validEmail(email))errors.email='Enter a valid email address.';if(!password)errors.password='Password is required.';else if(password.length>128)errors.password='Password is too long.';if(Object.keys(errors).length)return validationError(res,errors);const user=await User.findOne({email}).select('+password');if(!user||!(await user.comparePassword(password)))return res.status(401).json({message:'Invalid email or password'});if(user.role!=='admin'&&!user.emailVerified)return res.status(403).json({message:'Verify your email address before signing in.',code:'EMAIL_NOT_VERIFIED',email:user.email});if(user.status!=='active')return res.status(403).json({message:'Your account is not currently active'});const token=signAccessToken(user);setAuthCookie(res,token);await User.updateOne({_id:user._id},{$set:{lastLoginAt:new Date()}});return res.json({user:{id:user._id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role,emailVerified:user.emailVerified}});}

export async function forgotPassword(req,res){const email=clean(req.body?.email,254).toLowerCase();if(!validEmail(email))return res.json(genericReset);const user=await User.findOne({email,status:{$ne:'suspended'}}).select('+passwordResetTokenHash +passwordResetExpiresAt');if(!user)return res.json(genericReset);if(user.passwordResetExpiresAt&&user.passwordResetExpiresAt>new Date(Date.now()+29*60*1000))return res.json(genericReset);const token=crypto.randomBytes(32).toString('hex');user.passwordResetTokenHash=tokenHash(token);user.passwordResetExpiresAt=new Date(Date.now()+30*60*1000);await user.save({validateBeforeSave:false});const resetUrl=`${process.env.CLIENT_URL}/reset-password?token=${encodeURIComponent(token)}`;const html=brandedEmail({eyebrow:'Account security',title:'Reset your password',greeting:`Hello ${user.firstName},`,paragraphs:['We received a request to reset the password for your Royalties Service Connect account.','Use the secure button below to choose a new password. The reset link expires in 30 minutes.'],buttonLabel:'Reset password',buttonUrl:resetUrl,note:'If you did not request this password reset, you can safely ignore this email. Your current password will remain unchanged.'});const text=`Hello ${user.firstName},\n\nWe received a request to reset your Royalties Service Connect password.\n\nReset your password: ${resetUrl}\n\nThis link expires in 30 minutes.`;try{const result=await sendEmail({to:user.email,subject:'Reset your RB Service Connect password',html,text});if(result.skipped&&process.env.NODE_ENV!=='production')console.info(`Password reset link for ${user.email}: ${resetUrl}`);}catch(error){user.passwordResetTokenHash=null;user.passwordResetExpiresAt=null;await user.save({validateBeforeSave:false});throw error;}return res.json(genericReset);}

export async function resetPassword(req,res){const token=String(req.body?.token||''),password=String(req.body?.password||'');const errors={};if(!/^[a-f\d]{64}$/i.test(token))errors.token='This password reset link is invalid or has expired.';if(!validPassword(password))errors.password='Password must be 8–128 characters and include at least one letter and one number.';if(Object.keys(errors).length)return validationError(res,errors);const user=await User.findOne({passwordResetTokenHash:tokenHash(token),passwordResetExpiresAt:{$gt:new Date()},status:{$ne:'suspended'}}).select('+password +passwordResetTokenHash +passwordResetExpiresAt');if(!user)return res.status(400).json({message:'This password reset link is invalid or has expired'});if(await user.comparePassword(password))return validationError(res,{password:'Choose a password different from your current password.'});user.password=password;user.passwordResetTokenHash=null;user.passwordResetExpiresAt=null;user.emailVerificationTokenHash=null;user.emailVerificationExpiresAt=null;await user.save();clearAuthCookie(res);return res.json({message:'Password reset successfully. Sign in again with your new password.'});}
export function logout(_req,res){clearAuthCookie(res);return res.status(204).send();}
export function me(req,res){return res.json({user:req.user});}
