import User from '../models/User.js';
import { setAuthCookie, signAccessToken } from '../utils/tokens.js';

export async function register(req,res){const {firstName,lastName,email,password,role='candidate'}=req.body;if(!firstName||!lastName||!email||!password)return res.status(400).json({message:'All required fields must be provided'});if(!['candidate','recruiter'].includes(role))return res.status(400).json({message:'Invalid account role'});if(password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});const existing=await User.findOne({email:email.toLowerCase()});if(existing)return res.status(409).json({message:'An account with this email already exists'});const user=await User.create({firstName,lastName,email,password,role,status:role==='recruiter'?'pending':'active'});return res.status(201).json({message:role==='recruiter'?'Recruiter account created and awaiting approval':'Account created successfully',user:{id:user._id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role,status:user.status}});}

export async function login(req,res){const {email,password}=req.body;if(!email||!password)return res.status(400).json({message:'Email and password are required'});const user=await User.findOne({email:email.toLowerCase()}).select('+password');if(!user||!(await user.comparePassword(password)))return res.status(401).json({message:'Invalid email or password'});if(user.status!=='active')return res.status(403).json({message:'Your account is not currently active'});user.lastLoginAt=new Date();await user.save({validateBeforeSave:false});const token=signAccessToken(user);setAuthCookie(res,token);return res.json({user:{id:user._id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role}});}

export function logout(_req,res){res.clearCookie('rbsc_token',{path:'/'});return res.status(204).send();}
export function me(req,res){return res.json({user:req.user});}
