import PaymentTransaction from '../models/PaymentTransaction.js';
import SuccessFee from '../models/SuccessFee.js';
import { createNotification } from '../services/notificationService.js';

const money=(value)=>Math.max(0,Math.round(Number(value)||0));
const text=(value,max=1000)=>String(value||'').trim().slice(0,max);
function refreshSchedule(fee,now=new Date()){if(!fee.billing?.activatedAt)return;let paid=0;for(const installment of fee.billing.installments){if(installment.status==='paid'){paid+=installment.amount;continue;}if(installment.status==='waived')continue;installment.status=new Date(installment.dueAt)<now?'overdue':'scheduled';}const open=fee.billing.installments.filter((item)=>!['paid','waived'].includes(item.status)).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));if(open[0]&&new Date(open[0].dueAt)<=now&&open[0].status!=='overdue')open[0].status='due';fee.billing.paidAmount=paid;fee.billing.outstandingAmount=Math.max(0,fee.billing.totalAmount-paid);fee.billing.nextDueAt=open[0]?.dueAt||null;if(!open.length){fee.status='paid';fee.payment.paidAt=fee.payment.paidAt||now;}else if(paid>0)fee.status='partially_paid';else fee.status='payment_due';}
async function hydrateFee(id){return SuccessFee.findById(id).populate('company','name').populate('job','title slug').populate('candidate','firstName lastName email').lean();}
export async function getCandidateBilling(req,res){const fees=await SuccessFee.find({candidate:req.user._id,'billing.activatedAt':{$ne:null}}).populate('company','name').populate('job','title slug').sort({'billing.activatedAt':-1});for(const fee of fees){refreshSchedule(fee);await fee.save();}const ids=fees.map((item)=>item._id);const transactions=ids.length?await PaymentTransaction.find({candidate:req.user._id,successFee:{$in:ids}}).sort({createdAt:-1}).lean():[];return res.json({fees:fees.map((item)=>item.toObject()),transactions});}
export async function listAdminBilling(req,res){const fees=await SuccessFee.find({'billing.activatedAt':{$ne:null}}).populate('candidate','firstName lastName email').populate('company','name').populate('job','title slug').sort({'billing.nextDueAt':1});for(const fee of fees){refreshSchedule(fee);await fee.save();}const transactions=await PaymentTransaction.find({}).populate('candidate','firstName lastName email').sort({createdAt:-1}).limit(250).lean();const summary=fees.reduce((acc,fee)=>{acc.total+=fee.billing.totalAmount||0;acc.paid+=fee.billing.paidAmount||0;acc.outstanding+=fee.billing.outstandingAmount||0;if(fee.billing.installments.some((item)=>item.status==='overdue'))acc.overdue+=1;return acc;},{total:0,paid:0,outstanding:0,overdue:0});return res.json({fees:fees.map((item)=>item.toObject()),transactions,summary});}
export async function recordAdminPayment(req,res){const fee=await SuccessFee.findById(req.params.id);if(!fee||!fee.billing?.activatedAt)return res.status(404).json({message:'Active billing record not found.'});if(['waived','cancelled'].includes(fee.status))return res.status(400).json({message:'Payments cannot be recorded for this billing record.'});const number=Number(req.body.installmentNumber);const installment=fee.billing.installments.find((item)=>item.number===number);if(!installment)return res.status(404).json({message:'Installment not found.'});if(installment.status==='paid')return res.status(400).json({message:'This installment is already paid.'});const amount=money(req.body.amount||installment.amount);if(amount!==installment.amount)return res.status(400).json({message:'Recorded amount must match the installment amount.'});const reference=text(req.body.reference,180);const method=['gateway','upi','bank_transfer','cash','other'].includes(req.body.method)?req.body.method:'other';const paidAt=req.body.paidAt?new Date(req.body.paidAt):new Date();if(Number.isNaN(paidAt.getTime())||paidAt>new Date())return res.status(400).json({message:'Enter a valid payment date.'});const transaction=await PaymentTransaction.create({successFee:fee._id,candidate:fee.candidate,installmentNumber:number,amount,currency:fee.currency,status:'paid',method,provider:method==='gateway'?'manual-gateway':'manual',reference,paidAt,recordedBy:req.user._id,notes:text(req.body.notes)});installment.status='paid';installment.paidAt=paidAt;installment.providerPaymentId=reference;refreshSchedule(fee);if(fee.status==='paid'){fee.payment.provider='manual';fee.payment.paymentId=reference;fee.payment.paidAt=paidAt;}await fee.save();await createNotification({user:fee.candidate,type:'payment',title:'Career programme payment recorded',message:`Payment of ₹${amount.toLocaleString('en-IN')} was recorded for instalment ${number}.`,link:'/candidate/billing',metadata:{successFeeId:fee._id,transactionId:transaction._id}});return res.json({message:'Payment recorded successfully.',fee:await hydrateFee(fee._id),transaction});}
