import mongoose from 'mongoose';
import CandidateProfile from '../models/CandidateProfile.js';
import JobAlert from '../models/JobAlert.js';
import { listUserNotifications, markAllNotificationsRead, markNotificationRead } from '../services/notificationService.js';
import { validationError } from '../utils/validation.js';

const clean=(value='')=>String(value).trim();const allowedWorkModes=['','on-site','hybrid','remote'];const allowedTypes=['','full-time','part-time','contract','internship','temporary'];const allowedFrequencies=['instant','daily','weekly'];
async function profileFor(userId){return CandidateProfile.findOneAndUpdate({user:userId},{$setOnInsert:{user:userId}},{new:true,upsert:true,setDefaultsOnInsert:true});}
function bool(value,fallback=true){return typeof value==='boolean'?value:fallback;}
function alertPayload(body={},current=null){return {name:clean(body.name??current?.name).slice(0,120),keywords:clean(body.keywords??current?.keywords).slice(0,300),location:clean(body.location??current?.location).slice(0,160),category:clean(body.category??current?.category).slice(0,100),workMode:allowedWorkModes.includes(body.workMode??current?.workMode)?(body.workMode??current?.workMode):'',employmentType:allowedTypes.includes(body.employmentType??current?.employmentType)?(body.employmentType??current?.employmentType):'',frequency:allowedFrequencies.includes(body.frequency??current?.frequency)?(body.frequency??current?.frequency):'instant',emailEnabled:bool(body.emailEnabled,current?.emailEnabled??true),inAppEnabled:bool(body.inAppEnabled,current?.inAppEnabled??true),active:bool(body.active,current?.active??true)};}
function alertErrors(payload){const errors={};if(payload.name.length<2)errors.name='Alert name must be at least 2 characters.';if(!payload.keywords&&!payload.location&&!payload.category&&!payload.workMode&&!payload.employmentType)errors.conditions='Add at least one matching condition.';if(!payload.emailEnabled&&!payload.inAppEnabled)errors.delivery='Keep at least one alert delivery channel enabled.';return errors;}
function validId(value){return mongoose.isValidObjectId(value);}
export async function listJobAlerts(req,res){const alerts=await JobAlert.find({candidate:req.user._id}).sort({createdAt:-1}).lean();return res.json({alerts});}
export async function createJobAlert(req,res){const payload=alertPayload(req.body),errors=alertErrors(payload);if(Object.keys(errors).length)return validationError(res,errors);const duplicate=await JobAlert.findOne({candidate:req.user._id,name:{$regex:`^${payload.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,$options:'i'}}).lean();if(duplicate)return res.status(409).json({message:'You already have a job alert with this name.',errors:{name:'Choose a different alert name.'}});const alert=await JobAlert.create({...payload,candidate:req.user._id});return res.status(201).json({message:'Job alert created.',alert});}
export async function updateJobAlert(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid job alert reference.'});const current=await JobAlert.findOne({_id:req.params.id,candidate:req.user._id});if(!current)return res.status(404).json({message:'Job alert not found.'});const payload=alertPayload(req.body,current),errors=alertErrors(payload);if(Object.keys(errors).length)return validationError(res,errors);const duplicate=await JobAlert.findOne({candidate:req.user._id,_id:{$ne:current._id},name:{$regex:`^${payload.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,$options:'i'}}).lean();if(duplicate)return res.status(409).json({message:'You already have a job alert with this name.',errors:{name:'Choose a different alert name.'}});Object.assign(current,payload);await current.save();return res.json({message:'Job alert updated.',alert:current});}
export async function deleteJobAlert(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid job alert reference.'});const alert=await JobAlert.findOneAndDelete({_id:req.params.id,candidate:req.user._id});if(!alert)return res.status(404).json({message:'Job alert not found.'});return res.json({message:'Job alert deleted.'});}
export async function getNotifications(req,res){return res.json(await listUserNotifications(req.user._id,{limit:req.query.limit}));}
export async function readNotification(req,res){if(!validId(req.params.id))return res.status(400).json({message:'Invalid notification reference.'});const notification=await markNotificationRead(req.user._id,req.params.id);if(!notification)return res.status(404).json({message:'Notification not found.'});return res.json({message:'Notification marked as read.',notification});}
export async function readAllNotifications(req,res){const count=await markAllNotificationsRead(req.user._id);return res.json({message:count?'Notifications marked as read.':'No unread notifications.',count});}
export async function getPrivacy(req,res){const profile=await profileFor(req.user._id);return res.json({privacy:profile.privacy});}
export async function updatePrivacy(req,res){const profile=await profileFor(req.user._id);const current=profile.privacy||{};profile.privacy={discoverableToRecruiters:bool(req.body.discoverableToRecruiters,current.discoverableToRecruiters??true),showResumeToRecruiters:bool(req.body.showResumeToRecruiters,current.showResumeToRecruiters??true),jobAlertsEnabled:bool(req.body.jobAlertsEnabled,current.jobAlertsEnabled??true),recruiterMessagesEnabled:bool(req.body.recruiterMessagesEnabled,current.recruiterMessagesEnabled??true)};await profile.save();if(profile.privacy.jobAlertsEnabled===false)await JobAlert.updateMany({candidate:req.user._id,active:true},{$set:{active:false}});return res.json({message:'Privacy preferences updated.',privacy:profile.privacy});}
