import crypto from 'node:crypto';
import Application from '../models/Application.js';
import CandidateProfile from '../models/CandidateProfile.js';
import Job from '../models/Job.js';
import User from '../models/User.js';
import { createNotification } from '../services/notificationService.js';
import { validPassword,validPhone,validUrl,validationError } from '../utils/validation.js';

const cleanArray=(value,max=30)=>Array.isArray(value)?value.map((item)=>String(item).trim()).filter(Boolean).slice(0,max):[];
const sanitizeProfile=(body={})=>({headline:String(body.headline||'').trim().slice(0,160),phone:String(body.phone||'').trim().slice(0,20),location:String(body.location||'').trim().slice(0,160),bio:String(body.bio||'').trim().slice(0,2000),portfolioUrl:String(body.portfolioUrl||'').trim().slice(0,500),linkedinUrl:String(body.linkedinUrl||'').trim().slice(0,500),skills:cleanArray(body.skills,40).map((item)=>item.slice(0,80)),experience:Array.isArray(body.experience)?body.experience.slice(0,20).map((item)=>({title:String(item.title||'').trim().slice(0,120),company:String(item.company||'').trim().slice(0,120),location:String(item.location||'').trim().slice(0,160),startDate:String(item.startDate||'').trim().slice(0,40),endDate:String(item.endDate||'').trim().slice(0,40),current:Boolean(item.current),description:String(item.description||'').trim().slice(0,1500)})):[],education:Array.isArray(body.education)?body.education.slice(0,20).map((item)=>({institution:String(item.institution||'').trim().slice(0,160),degree:String(item.degree||'').trim().slice(0,120),field:String(item.field||'').trim().slice(0,120),startYear:String(item.startYear||'').trim().slice(0,4),endYear:String(item.endYear||'').trim().slice(0,4)})):[],preferences:{jobTypes:cleanArray(body.preferences?.jobTypes,10).map((item)=>item.slice(0,80)),workplaces:cleanArray(body.preferences?.workplaces,10).map((item)=>item.slice(0,80)),preferredLocations:cleanArray(body.preferences?.preferredLocations,15).map((item)=>item.slice(0,120)),minimumSalary:String(body.preferences?.minimumSalary||'').trim().slice(0,40),openToWork:body.preferences?.openToWork!==false}});
function validateProfile(payload){const errors={};if(payload.headline.length<2)errors.headline='Headline must be at least 2 characters.';if(payload.phone&&!validPhone(payload.phone))errors.phone='Enter a valid 10-digit Indian mobile number.';if(payload.location.length<2)errors.location='Location must be at least 2 characters.';if(payload.portfolioUrl&&!validUrl(payload.portfolioUrl))errors.portfolioUrl='Enter a valid portfolio URL.';if(payload.linkedinUrl&&!validUrl(payload.linkedinUrl))errors.linkedinUrl='Enter a valid LinkedIn URL.';payload.experience.forEach((item,index)=>{if(item.title||item.company||item.description){if(item.title.length<2)errors[`experience.${index}.title`]='Job title must be at least 2 characters.';if(item.company.length<2)errors[`experience.${index}.company`]='Company must be at least 2 characters.';if(item.current&&item.endDate)errors[`experience.${index}.endDate`]='Current roles should not have an end date.';}});payload.education.forEach((item,index)=>{if(item.institution||item.degree||item.field){if(item.institution.length<2)errors[`education.${index}.institution`]='Institution must be at least 2 characters.';if(item.degree.length<2)errors[`education.${index}.degree`]='Degree must be at least 2 characters.';const start=Number(item.startYear||0),end=Number(item.endYear||0);if(start&&(start<1950||start>2100))errors[`education.${index}.startYear`]='Enter a valid start year.';if(end&&(end<1950||end>2100))errors[`education.${index}.endYear`]='Enter a valid end year.';if(start&&end&&end<start)errors[`education.${index}.endYear`]='End year cannot be before start year.';}});return errors;}
function completion(profile,user){const checks=[user.firstName,user.lastName,profile?.headline,profile?.phone,profile?.location,profile?.bio,profile?.skills?.length,profile?.experience?.length,profile?.education?.length,profile?.resume?.url,profile?.preferences?.jobTypes?.length,profile?.preferences?.workplaces?.length];return Math.round((checks.filter(Boolean).length/checks.length)*100);}
async function getOrCreateProfile(userId){return CandidateProfile.findOneAndUpdate({user:userId},{$setOnInsert:{user:userId}},{new:true,upsert:true,setDefaultsOnInsert:true});}
function cloudinaryConfig(){const {CLOUDINARY_CLOUD_NAME:cloudName,CLOUDINARY_API_KEY:apiKey,CLOUDINARY_API_SECRET:apiSecret}=process.env;return cloudName&&apiKey&&apiSecret?{cloudName,apiKey,apiSecret}:null;}
function signature(params,secret){const value=Object.entries(params).sort(([a],[b])=>a.localeCompare(b)).map(([key,val])=>`${key}=${val}`).join('&');return crypto.createHash('sha1').update(`${value}${secret}`).digest('hex');}
async function deleteManagedResume(resume){const config=cloudinaryConfig();if(!config||!resume?.publicId)return;const timestamp=Math.floor(Date.now()/1000);const form=new FormData();form.append('public_id',resume.publicId);form.append('timestamp',String(timestamp));form.append('api_key',config.apiKey);form.append('signature',signature({public_id:resume.publicId,timestamp},config.apiSecret));try{await fetch(`https://api.cloudinary.com/v1_1/${config.cloudName}/raw/destroy`,{method:'POST',body:form});}catch(error){console.error('Unable to remove previous candidate resume.',error);}}
function salaryText(s={}){if(!s.min&&!s.max)return 'Salary not disclosed';const fmt=(v)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);return `${s.min?fmt(s.min):''}${s.min&&s.max?' – ':''}${s.max?fmt(s.max):''} / ${s.period||'year'}`;}
function serialize(job){const c=job.company||{};const name=c.name||'Employer';return {slug:job.slug,title:job.title,company:name,initials:name.split(/\s+/).slice(0,2).map((p)=>p[0]?.toUpperCase()).join(''),location:[job.location?.city,job.location?.state,job.location?.country].filter(Boolean).join(', ')||'India',workplace:job.workMode==='on-site'?'On-site':job.workMode?.[0]?.toUpperCase()+job.workMode?.slice(1),type:job.employmentType?.split('-').map((p)=>p[0]?.toUpperCase()+p.slice(1)).join('-'),experience:job.experience||'Not specified',salary:salaryText(job.salary),category:job.category||'Other',skills:job.skills||[]};}
export async function getOverview(req,res){const userId=req.user._id;const [profile,recentApplications,totalApplications,activeApplications,interviews]=await Promise.all([getOrCreateProfile(userId),Application.find({candidate:userId}).sort({updatedAt:-1}).limit(4).lean(),Application.countDocuments({candidate:userId}),Application.countDocuments({candidate:userId,status:{$nin:['rejected','withdrawn','hired']}}),Application.countDocuments({candidate:userId,status:'interview'})]);const savedDocs=await Job.find({slug:{$in:profile.savedJobs||[]},status:'published'}).populate('company','name').lean();return res.json({profileCompletion:completion(profile,req.user),counts:{activeApplications,savedJobs:savedDocs.length,interviews,totalApplications},recentApplications,savedJobs:savedDocs.map(serialize).slice(0,4),profile});}
export async function getProfile(req,res){const profile=await getOrCreateProfile(req.user._id);return res.json({profile,completion:completion(profile,req.user)});}
export async function updateProfile(req,res){const payload=sanitizeProfile(req.body);const errors=validateProfile(payload);if(Object.keys(errors).length)return validationError(res,errors);const profile=await CandidateProfile.findOneAndUpdate({user:req.user._id},{$set:payload},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});return res.json({message:'Profile updated.',profile,completion:completion(profile,req.user)});}
export async function updateResume(req,res){const name=String(req.body.name||'').trim();const url=String(req.body.url||'').trim();if(!name||!url)return res.status(400).json({message:'Resume name and URL are required.'});try{new URL(url);}catch{return res.status(400).json({message:'Enter a valid resume URL.'});}const profile=await getOrCreateProfile(req.user._id);if(profile.resume?.source==='upload')await deleteManagedResume(profile.resume);profile.resume={name,url,publicId:'',source:'url',updatedAt:new Date()};await profile.save();return res.json({message:'Resume updated.',resume:profile.resume});}
export async function uploadResume(req,res){const config=cloudinaryConfig();if(!config)return res.status(503).json({message:'Resume uploads are not configured yet. Add Cloudinary credentials on the server.'});const name=String(req.body.name||'').trim();const dataUrl=String(req.body.dataUrl||'');if(!name||!dataUrl)return res.status(400).json({message:'Choose a PDF resume to upload.'});if(!name.toLowerCase().endsWith('.pdf')||!dataUrl.startsWith('data:application/pdf;base64,'))return res.status(400).json({message:'Only PDF resumes are allowed.'});const encoded=dataUrl.split(',')[1]||'';if(Math.ceil(encoded.length*3/4)>5*1024*1024)return res.status(413).json({message:'Resume must be 5 MB or smaller.'});const timestamp=Math.floor(Date.now()/1000);const folder='rb-service-connect/candidate-resumes';const publicId=`candidate-${req.user._id}-${Date.now()}`;const params={folder,public_id:publicId,timestamp};const form=new FormData();form.append('file',dataUrl);form.append('api_key',config.apiKey);form.append('timestamp',String(timestamp));form.append('folder',folder);form.append('public_id',publicId);form.append('signature',signature(params,config.apiSecret));const response=await fetch(`https://api.cloudinary.com/v1_1/${config.cloudName}/raw/upload`,{method:'POST',body:form});const result=await response.json();if(!response.ok||!result.secure_url)return res.status(502).json({message:'Resume upload failed. Please try again.'});const profile=await getOrCreateProfile(req.user._id);if(profile.resume?.source==='upload')await deleteManagedResume(profile.resume);profile.resume={name,url:result.secure_url,publicId:result.public_id,source:'upload',updatedAt:new Date()};await profile.save();return res.status(201).json({message:'Resume uploaded successfully.',resume:profile.resume});}
export async function deleteResume(req,res){const profile=await getOrCreateProfile(req.user._id);if(profile.resume?.source==='upload')await deleteManagedResume(profile.resume);profile.resume={name:'',url:'',publicId:'',source:'',updatedAt:null};await profile.save();return res.json({message:'Resume removed.'});}
export async function getSavedJobs(req,res){const profile=await getOrCreateProfile(req.user._id);const docs=await Job.find({slug:{$in:profile.savedJobs||[]},status:'published'}).populate('company','name').lean();return res.json({jobs:docs.map(serialize)});}
export async function saveJob(req,res){const job=await Job.findOne({slug:req.params.slug,status:{$in:['published','reviewing']}});if(!job)return res.status(404).json({message:'Job not found.'});const profile=await getOrCreateProfile(req.user._id);if(!profile.savedJobs.includes(job.slug)){profile.savedJobs.push(job.slug);await profile.save();}return res.json({message:'Job saved.',savedJobs:profile.savedJobs});}
export async function unsaveJob(req,res){const profile=await getOrCreateProfile(req.user._id);profile.savedJobs=profile.savedJobs.filter((slug)=>slug!==req.params.slug);await profile.save();return res.json({message:'Job removed from saved jobs.',savedJobs:profile.savedJobs});}
export async function listApplications(req,res){const applications=await Application.find({candidate:req.user._id}).sort({createdAt:-1}).lean();return res.json({applications});}
export async function createApplication(req,res){const job=await Job.findOne({slug:String(req.body.jobSlug||''),status:'published'}).populate('company','name');if(!job)return res.status(404).json({message:'Job not found or no longer accepting applications.'});if(job.applicationDeadline&&job.applicationDeadline<=new Date())return res.status(409).json({message:'The application window for this job has closed.',code:'APPLICATION_CLOSED'});const existing=await Application.findOne({candidate:req.user._id,jobSlug:job.slug});if(existing)return res.status(409).json({message:'You have already applied for this job.'});const profile=await getOrCreateProfile(req.user._id);if(!profile.resume?.url)return res.status(400).json({message:'A resume is required before you can apply. Upload your resume from the Resume section and try again.',code:'RESUME_REQUIRED'});const coverLetter=String(req.body.coverLetter||'').trim().slice(0,5000);const application=await Application.create({job:job._id,candidate:req.user._id,jobSlug:job.slug,jobSnapshot:serialize(job),resumeUrl:profile.resume.url,coverLetter});await createNotification({user:job.createdBy,type:'new_application',title:`New application for ${job.title}`,message:`${req.user.firstName} ${req.user.lastName} applied for ${job.title}.`,link:'/recruiter/applicants',metadata:{applicationId:application._id,jobId:job._id,candidateId:req.user._id}});return res.status(201).json({message:'Application submitted.',application});}
export async function withdrawApplication(req,res){const application=await Application.findOne({_id:req.params.id,candidate:req.user._id});if(!application)return res.status(404).json({message:'Application not found.'});if(['hired','rejected','withdrawn'].includes(application.status))return res.status(400).json({message:'This application can no longer be withdrawn.'});application.status='withdrawn';application.withdrawnAt=new Date();application.statusHistory.push({status:'withdrawn',note:'Application withdrawn by candidate.',changedBy:req.user._id});await application.save();return res.json({message:'Application withdrawn.',application});}
export async function getRecommendedJobs(req,res){const profile=await getOrCreateProfile(req.user._id);const appliedSlugs=new Set((await Application.find({candidate:req.user._id}).select('jobSlug').lean()).map((item)=>item.jobSlug));const docs=await Job.find({status:'published',slug:{$nin:[...appliedSlugs]},$or:[{applicationDeadline:null},{applicationDeadline:{$gt:new Date()}}]}).populate('company','name').sort({publishedAt:-1}).limit(30).lean();const preferredWorkplaces=new Set((profile.preferences?.workplaces||[]).map((item)=>item.toLowerCase()));const ranked=docs.map((job)=>({job,score:(preferredWorkplaces.has(job.workMode?.toLowerCase())?2:0)+((job.skills||[]).some((skill)=>(profile.skills||[]).some((candidateSkill)=>candidateSkill.toLowerCase()===skill.toLowerCase()))?3:0)})).sort((a,b)=>b.score-a.score).slice(0,4).map(({job})=>serialize(job));return res.json({jobs:ranked});}
export async function updateAccount(req,res){const firstName=String(req.body.firstName||'').trim().slice(0,60),lastName=String(req.body.lastName||'').trim().slice(0,60);const errors={};if(firstName.length<2)errors.firstName='First name must be at least 2 characters.';if(lastName.length<2)errors.lastName='Last name must be at least 2 characters.';if(Object.keys(errors).length)return validationError(res,errors);const user=await User.findByIdAndUpdate(req.user._id,{$set:{firstName,lastName}},{new:true,runValidators:true}).select('-password');return res.json({message:'Account updated.',user});}
export async function changePassword(req,res){const currentPassword=String(req.body.currentPassword||''),newPassword=String(req.body.newPassword||'');const errors={};if(!currentPassword)errors.currentPassword='Current password is required.';if(!validPassword(newPassword))errors.newPassword='New password must be 8–128 characters and include at least one letter and one number.';if(Object.keys(errors).length)return validationError(res,errors);const user=await User.findById(req.user._id).select('+password');if(!user||!(await user.comparePassword(currentPassword)))return validationError(res,{currentPassword:'Current password is incorrect.'});user.password=newPassword;await user.save();return res.json({message:'Password changed successfully.'});}
