import SuccessFee from '../models/SuccessFee.js';
import { createNotification } from '../services/notificationService.js';
import { activateBillingSchedule,reconcileHireConfirmations } from '../services/successFeeService.js';
import { validationError } from '../utils/validation.js';
const cleanDate=(value)=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};const salary=(value)=>Math.max(0,Math.round(Number(value)||0));
async function populatedFee(id){return SuccessFee.findById(id).populate('candidate','firstName lastName email').populate('recruiter','firstName lastName email').populate('company','name').populate('job','title slug').lean();}
function confirmationErrors(amount,startDate){const errors={};if(!amount)errors.salaryAmount='Enter a valid salary amount greater than zero.';if(!startDate)errors.startDate='Choose a valid joining date.';else if(startDate>new Date(Date.now()+365*24*60*60*1000))errors.startDate='Joining date cannot be more than one year in the future.';return errors;}
const editablePlacementStatuses=new Set(['awaiting_hire_confirmation','awaiting_candidate_confirmation','awaiting_first_salary','disputed']);
function ensureConfirmationEditable(fee,res){if(fee.billing?.activatedAt||fee.firstSalary?.received||['payment_due','partially_paid','paid','waived','cancelled'].includes(fee.status)){res.status(409).json({message:'Placement details are locked because billing has started or the placement is closed.'});return false;}if(!editablePlacementStatuses.has(fee.status)){res.status(409).json({message:'This placement can no longer be changed.'});return false;}return true;}
function sameConfirmation(current,amount,startDate){return Boolean(current?.confirmed)&&Number(current.salaryAmount)===amount&&current.startDate&&new Date(current.startDate).getTime()===startDate.getTime();}
function resetReconciliationForChangedConfirmation(fee){if(fee.status==='awaiting_first_salary'||fee.status==='disputed'){fee.status='awaiting_candidate_confirmation';fee.firstSalaryAmount=0;fee.dispute={reason:'',openedBy:null,openedAt:null,resolvedAt:null,resolution:''};}}
export async function listCandidatePlacements(req,res){const placements=await SuccessFee.find({candidate:req.user._id}).populate('company','name').populate('job','title slug').sort({createdAt:-1}).lean();return res.json({placements});}
export async function confirmCandidateHire(req,res){const fee=await SuccessFee.findOne({_id:req.params.id,candidate:req.user._id});if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(!ensureConfirmationEditable(fee,res))return;const amount=salary(req.body.salaryAmount),startDate=cleanDate(req.body.startDate),errors=confirmationErrors(amount,startDate);if(Object.keys(errors).length)return validationError(res,errors);if(sameConfirmation(fee.candidateConfirmation,amount,startDate))return res.status(409).json({message:'These candidate placement details are already confirmed.'});resetReconciliationForChangedConfirmation(fee);fee.candidateConfirmation={confirmed:true,salaryAmount:amount,startDate,confirmedAt:new Date()};reconcileHireConfirmations(fee);await fee.save();await createNotification({user:fee.recruiter,type:'placement_confirmation',title:'Candidate confirmed placement',message:'The candidate confirmed their joining details. Placement verification has been updated.',link:'/recruiter/placements',metadata:{successFeeId:fee._id}});return res.json({message:fee.status==='disputed'?'Confirmation saved. The details need review because the salary figures do not match.':'Placement confirmation saved.',placement:await populatedFee(fee._id)});}
export async function confirmFirstSalary(req,res){const fee=await SuccessFee.findOne({_id:req.params.id,candidate:req.user._id});if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(fee.billing?.activatedAt||fee.firstSalary?.received)return res.status(409).json({message:'First salary has already been confirmed and billing is active.'});if(fee.status!=='awaiting_first_salary'||!fee.candidateConfirmation?.confirmed||!fee.recruiterConfirmation?.confirmed)return res.status(400).json({message:'First salary can only be confirmed after both placement confirmations match.'});const receivedAt=cleanDate(req.body.receivedAt)||new Date();if(receivedAt>new Date())return validationError(res,{receivedAt:'Salary receipt date cannot be in the future.'});const joiningDates=[fee.candidateConfirmation.startDate,fee.recruiterConfirmation.startDate].filter(Boolean).map((value)=>new Date(value));const latestJoining=joiningDates.length?new Date(Math.max(...joiningDates.map((value)=>value.getTime()))):null;if(latestJoining&&receivedAt<latestJoining)return validationError(res,{receivedAt:'Salary receipt date cannot be before the confirmed joining date.'});fee.firstSalary={received:true,receivedAt,confirmedAt:new Date()};activateBillingSchedule(fee,new Date());await fee.save();return res.json({message:fee.paymentPreference==='full'?'First salary confirmed. Your agreed Career Programme fee is now due.':'First salary confirmed. Your agreed Career Programme instalment schedule is now active.',placement:await populatedFee(fee._id)});}
export async function listRecruiterPlacements(req,res){const placements=await SuccessFee.find({recruiter:req.user._id}).populate('candidate','firstName lastName email').populate('company','name').populate('job','title slug').sort({createdAt:-1}).lean();return res.json({placements});}
export async function confirmRecruiterHire(req,res){const fee=await SuccessFee.findOne({_id:req.params.id,recruiter:req.user._id});if(!fee)return res.status(404).json({message:'Placement verification not found.'});if(!ensureConfirmationEditable(fee,res))return;const amount=salary(req.body.salaryAmount),startDate=cleanDate(req.body.startDate),errors=confirmationErrors(amount,startDate);if(Object.keys(errors).length)return validationError(res,errors);if(sameConfirmation(fee.recruiterConfirmation,amount,startDate))return res.status(409).json({message:'These recruiter placement details are already confirmed.'});resetReconciliationForChangedConfirmation(fee);fee.recruiterConfirmation={confirmed:true,salaryAmount:amount,startDate,confirmedAt:new Date()};reconcileHireConfirmations(fee);if(fee.status==='awaiting_hire_confirmation'&&fee.recruiterConfirmation.confirmed)fee.status='awaiting_candidate_confirmation';await fee.save();await createNotification({user:fee.candidate,type:'placement_confirmation',title:'Confirm your placement details',message:'Your recruiter has confirmed your hire. Review and confirm the joining details.',link:'/candidate/placements',metadata:{successFeeId:fee._id}});return res.json({message:fee.status==='disputed'?'Confirmation saved. The details need review because the salary figures do not match.':'Hire confirmation saved.',placement:await populatedFee(fee._id)});}
