import crypto from 'node:crypto';
import mongoose from 'mongoose';
import { promotionProducts,publicPromotionCatalogue } from '../config/monetization.js';
import CandidateProfile from '../models/CandidateProfile.js';
import Job from '../models/Job.js';
import Promotion from '../models/Promotion.js';

function paymentConfig(){const keyId=String(process.env.RAZORPAY_KEY_ID||'').trim();const keySecret=String(process.env.RAZORPAY_KEY_SECRET||'').trim();if(!keyId||!keySecret){const error=new Error('Online promotion payments are not configured yet.');error.status=503;throw error;}return {keyId,keySecret};}
async function razorpayRequest(path,{method='GET',body}={}){const {keyId,keySecret}=paymentConfig();const response=await fetch(`https://api.razorpay.com/v1${path}`,{method,headers:{Authorization:`Basic ${Buffer.from(`${keyId}:${keySecret}`).toString('base64')}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data?.error?.description||'Payment provider request failed.');error.status=502;throw error;}return data;}
function safeSignature(orderId,paymentId,signature,secret){const expected=crypto.createHmac('sha256',secret).update(`${orderId}|${paymentId}`).digest('hex');const a=Buffer.from(expected,'hex');const b=Buffer.from(String(signature||''),'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
async function ownedTarget(req,product,targetId){if(product.targetType==='candidate-profile'){const target=await CandidateProfile.findOne({user:req.user._id});if(!target){const error=new Error('Complete your candidate profile before boosting it.');error.status=404;throw error;}return target;}if(!mongoose.isValidObjectId(targetId)){const error=new Error('Select a valid job to promote.');error.status=400;throw error;}const target=await Job.findOne({_id:targetId,createdBy:req.user._id});if(!target){const error=new Error('Job not found.');error.status=404;throw error;}if(!['published','reviewing'].includes(target.status)){const error=new Error('Only active jobs can be promoted.');error.status=400;throw error;}return target;}
export async function getPromotionCatalogue(req,res){return res.json({products:publicPromotionCatalogue(req.user.role),payment:{provider:'razorpay',enabled:Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),keyId:process.env.RAZORPAY_KEY_ID||''}});}
export async function listPromotions(req,res){await Promotion.updateMany({owner:req.user._id,status:'active',endsAt:{$lte:new Date()}},{$set:{status:'expired'}});const promotions=await Promotion.find({owner:req.user._id}).sort({createdAt:-1}).lean();return res.json({promotions});}
export async function createPromotion(req,res){try{const productId=String(req.body.product||'');const product=promotionProducts[productId];const durationDays=Number(req.body.durationDays);const targetId=String(req.body.targetId||'');if(!product||product.audience!==req.user.role)return res.status(400).json({message:'This promotion is not available for your account.'});const option=product.options.find((item)=>item.days===durationDays);if(!option)return res.status(400).json({message:'Select a valid promotion duration.'});const target=await ownedTarget(req,product,targetId);const existing=await Promotion.findOne({owner:req.user._id,product:productId,target:target._id,status:{$in:['pending','active']}});if(existing)return res.status(409).json({message:'This promotion already has a pending or active purchase.'});const promotion=await Promotion.create({owner:req.user._id,audience:req.user.role,product:productId,targetType:product.targetType,target:target._id,durationDays,amount:option.amount,currency:'INR',payment:{provider:'razorpay'}});const order=await razorpayRequest('/orders',{method:'POST',body:{amount:Math.round(option.amount*100),currency:'INR',receipt:`promo_${promotion._id}`,notes:{promotionId:String(promotion._id),ownerId:String(req.user._id),product:productId}}});promotion.payment.orderId=order.id;await promotion.save();return res.status(201).json({message:'Promotion order created.',promotion,checkout:{keyId:paymentConfig().keyId,orderId:order.id,amount:order.amount,currency:order.currency,name:'RB Service Connect',description:`${product.name} · ${durationDays} days`}});}catch(error){return res.status(error.status||500).json({message:error.message||'Unable to create promotion order.'});}}
export async function verifyPromotionPayment(req,res){try{const promotion=await Promotion.findOne({_id:req.params.id,owner:req.user._id});if(!promotion)return res.status(404).json({message:'Promotion order not found.'});if(promotion.status==='active')return res.json({message:'Promotion is already active.',promotion});if(promotion.status!=='pending'||!promotion.payment?.orderId)return res.status(409).json({message:'This promotion cannot be activated.'});const paymentId=String(req.body.razorpay_payment_id||'');const signature=String(req.body.razorpay_signature||'');const {keySecret}=paymentConfig();if(!paymentId||!signature||!safeSignature(promotion.payment.orderId,paymentId,signature,keySecret))return res.status(400).json({message:'Payment verification failed. Promotion was not activated.'});const payment=await razorpayRequest(`/payments/${encodeURIComponent(paymentId)}`);if(payment.order_id!==promotion.payment.orderId||payment.currency!=='INR'||Number(payment.amount)!==Math.round(promotion.amount*100)||!['captured','authorized'].includes(payment.status))return res.status(400).json({message:'Payment details do not match this promotion order.'});if(payment.status==='authorized')return res.status(409).json({message:'Payment is authorised but not captured yet. Please try again after capture completes.'});const startsAt=new Date();const endsAt=new Date(startsAt.getTime()+promotion.durationDays*86400000);promotion.status='active';promotion.startsAt=startsAt;promotion.endsAt=endsAt;promotion.payment.paymentId=paymentId;promotion.payment.paidAt=new Date((payment.created_at||Math.floor(Date.now()/1000))*1000);await promotion.save();return res.json({message:'Payment verified. Your promotion is now active.',promotion});}catch(error){return res.status(error.status||500).json({message:error.message||'Unable to verify payment.'});}}
