import Application from '../models/Application.js';
import Company from '../models/Company.js';
import Job from '../models/Job.js';
import Promotion from '../models/Promotion.js';
import User from '../models/User.js';

function formatSalary(salary={}){if(!salary.min&&!salary.max)return 'Salary not disclosed';const fmt=(value)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);return `${salary.min?fmt(salary.min):''}${salary.min&&salary.max?' – ':''}${salary.max?fmt(salary.max):''} / ${salary.period||'year'}`;}
function locationText(location={}){return [location.city,location.state,location.country].filter(Boolean).join(', ')||'India';}
function initials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]?.toUpperCase()).join('')||'RB';}
function accepting(job){return job.status==='published'&&(!job.applicationDeadline||new Date(job.applicationDeadline)>new Date());}
export function serializeJob(job,promotionProducts=[]){const company=job.company||{};const products=new Set(promotionProducts);return {id:job._id,slug:job.slug,title:job.title,company:company.name||'Employer',companySlug:company.slug||'',initials:initials(company.name),location:locationText(job.location),workplace:job.workMode==='on-site'?'On-site':job.workMode?.[0]?.toUpperCase()+job.workMode?.slice(1),type:job.employmentType?.split('-').map((p)=>p[0]?.toUpperCase()+p.slice(1)).join('-'),experience:job.experience||'Not specified',salary:formatSalary(job.salary),category:job.category||'Other',posted:job.publishedAt||job.createdAt,featured:Boolean(job.featured)||products.has('job-featured'),verified:company.verificationStatus==='verified',summary:job.summary||'',skills:job.skills||[],description:[job.description].filter(Boolean),responsibilities:job.responsibilities||[],requirements:job.requirements||[],benefits:job.benefits||[],hiringStatus:job.status,acceptingApplications:accepting(job),applicationDeadline:job.applicationDeadline||null,promotion:{sponsored:products.size>0,featured:products.has('job-featured'),searchBoost:products.has('job-search-boost'),urgent:products.has('job-urgent')}};}
async function activeJobPromotionMap(jobIds){if(!jobIds.length)return new Map();const now=new Date();const rows=await Promotion.find({target:{$in:jobIds},targetType:'job',status:'active',startsAt:{$lte:now},endsAt:{$gt:now}}).select('target product').lean();const map=new Map();for(const row of rows){const key=String(row.target);if(!map.has(key))map.set(key,[]);map.get(key).push(row.product);}return map;}
function promotionScore(products=[]){const set=new Set(products);return (set.has('job-featured')?100:0)+(set.has('job-search-boost')?60:0)+(set.has('job-urgent')?30:0);}

export async function getEmployerOverview(_req,res){const [activeRecruiters,totalRecruiters]=await Promise.all([User.countDocuments({role:'recruiter',status:'active'}),User.countDocuments({role:'recruiter'})]);return res.json({activeEmployerAccounts:activeRecruiters,registeredEmployerAccounts:totalRecruiters,approvalRequired:true,recruiterRegistrationOpen:true});}
export async function listPublicJobs(req,res){const query={status:{$in:['published','reviewing']}};if(req.query.company)query.company=req.query.company;const jobs=await Job.find(query).populate('company','name slug verificationStatus industry size location logoUrl').sort({featured:-1,publishedAt:-1,createdAt:-1}).lean();const promotions=await activeJobPromotionMap(jobs.map((job)=>job._id));jobs.sort((a,b)=>promotionScore(promotions.get(String(b._id)))-promotionScore(promotions.get(String(a._id))));return res.json({jobs:jobs.map((job)=>serializeJob(job,promotions.get(String(job._id))||[]))});}
export async function getPublicJob(req,res){const job=await Job.findOne({slug:req.params.slug,status:{$in:['published','reviewing']}}).populate('company','name slug verificationStatus industry size location logoUrl website description').lean();if(!job)return res.status(404).json({message:'Job not found.'});const promotions=await activeJobPromotionMap([job._id]);return res.json({job:serializeJob(job,promotions.get(String(job._id))||[])});}
export async function listPublicCompanies(_req,res){const companies=await Company.find({verificationStatus:'verified'}).sort({createdAt:-1}).lean();const ids=companies.map((c)=>c._id);const counts=await Job.aggregate([{$match:{company:{$in:ids},status:{$in:['published','reviewing']}}},{$group:{_id:'$company',count:{$sum:1}}}]);const map=new Map(counts.map((x)=>[String(x._id),x.count]));return res.json({companies:companies.map((c)=>({...c,openRoles:map.get(String(c._id))||0,initials:initials(c.name)}))});}
export async function getPublicCompany(req,res){const company=await Company.findOne({slug:req.params.slug,verificationStatus:'verified'}).lean();if(!company)return res.status(404).json({message:'Company not found.'});const jobs=await Job.find({company:company._id,status:{$in:['published','reviewing']}}).populate('company','name slug verificationStatus').sort({publishedAt:-1}).lean();const promotions=await activeJobPromotionMap(jobs.map((job)=>job._id));jobs.sort((a,b)=>promotionScore(promotions.get(String(b._id)))-promotionScore(promotions.get(String(a._id))));return res.json({company:{...company,initials:initials(company.name),openRoles:jobs.length},jobs:jobs.map((job)=>serializeJob(job,promotions.get(String(job._id))||[]))});}
export async function getPublicJobStats(_req,res){const [jobs,companies,applications]=await Promise.all([Job.countDocuments({status:{$in:['published','reviewing']}}),Company.countDocuments({verificationStatus:'verified'}),Application.countDocuments()]);return res.json({jobs,companies,applications});}
