import Application from '../models/Application.js';
import CandidateProfile from '../models/CandidateProfile.js';
import Company from '../models/Company.js';
import Job from '../models/Job.js';
import User from '../models/User.js';
import { brandedEmail, sendEmail } from '../services/emailService.js';
import { createNotification, notifyMatchingJobAlerts } from '../services/notificationService.js';
import { ensureSuccessFeeForHire } from '../services/successFeeService.js';
import { required, validUrl, validationError } from '../utils/validation.js';

const clean=(value='')=>String(value).trim();
const list=(value,max=30)=>Array.isArray(value)?value.map((item)=>clean(item)).filter(Boolean).slice(0,max):[];
const slugify=(value)=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,120);
const parseDate=(value)=>{if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};
const employmentTypes=['full-time','part-time','contract','internship','temporary'];
const workModes=['on-site','hybrid','remote'];
const salaryPeriods=['year','month','hour'];
async function getCompany(userId){return Company.findOne({owner:userId});}async function ownedJob(userId,id){return Job.findOne({_id:id,createdBy:userId});}
export async function getOverview(req,res){const company=await getCompany(req.user._id);if(!company)return res.json({company:null,counts:{jobs:0,publishedJobs:0,applications:0,interviews:0,offers:0},recentApplications:[]});const jobIds=await Job.find({createdBy:req.user._id}).distinct('_id');const [jobs,publishedJobs,applications,interviews,offers,recentApplications]=await Promise.all([Job.countDocuments({createdBy:req.user._id}),Job.countDocuments({createdBy:req.user._id,status:'published'}),Application.countDocuments({job:{$in:jobIds}}),Application.countDocuments({job:{$in:jobIds},status:'interview'}),Application.countDocuments({job:{$in:jobIds},status:'offered'}),Application.find({job:{$in:jobIds}}).sort({updatedAt:-1}).limit(6).populate('candidate','firstName lastName email').lean()]);return res.json({company,counts:{jobs,publishedJobs,applications,interviews,offers},recentApplications});}
export async function getCompanyProfile(req,res){return res.json({company:await getCompany(req.user._id)});}
export async function saveCompanyProfile(req,res){const payload={name:clean(req.body.name).slice(0,120),website:clean(req.body.website).slice(0,500),industry:clean(req.body.industry).slice(0,100),size:clean(req.body.size).slice(0,80),location:clean(req.body.location).slice(0,120),description:clean(req.body.description).slice(0,3000),logoUrl:clean(req.body.logoUrl).slice(0,500)};const errors={name:required(payload.name,'Company name',2,120),industry:required(payload.industry,'Industry',2,100),size:required(payload.size,'Company size',2,80),location:required(payload.location,'Location',2,120),description:required(payload.description,'Company description',30,3000),website:payload.website&&!validUrl(payload.website)?'Enter a valid website URL.':'',logoUrl:payload.logoUrl&&!validUrl(payload.logoUrl)?'Enter a valid logo URL.':''};for(const key of Object.keys(errors))if(!errors[key])delete errors[key];if(Object.keys(errors).length)return validationError(res,errors);let company=await getCompany(req.user._id);if(company){Object.assign(company,payload);if(company.verificationStatus==='rejected')company.verificationStatus='pending';await company.save();}else{let slug=slugify(payload.name)||`company-${Date.now()}`;if(await Company.exists({slug}))slug=`${slug}-${String(req.user._id).slice(-6)}`;company=await Company.create({...payload,slug,owner:req.user._id,verificationStatus:'pending'});}const message=company.verificationStatus==='verified'?'Company profile saved.':'Company profile saved and queued for verification.';return res.json({message,company});}
export async function listJobs(req,res){const jobs=await Job.find({createdBy:req.user._id}).sort({createdAt:-1}).lean();const ids=jobs.map((job)=>job._id);const counts=await Application.aggregate([{$match:{job:{$in:ids}}},{$group:{_id:'$job',count:{$sum:1}}}]);const map=new Map(counts.map((item)=>[String(item._id),item.count]));return res.json({jobs:jobs.map((job)=>({...job,applicants:map.get(String(job._id))||0}))});}
function jobPayload(body){return {title:clean(body.title),summary:clean(body.summary),description:clean(body.description),category:clean(body.category)||'Other',experience:clean(body.experience),responsibilities:list(body.responsibilities),requirements:list(body.requirements),benefits:list(body.benefits),skills:list(body.skills,40),employmentType:clean(body.employmentType),workMode:clean(body.workMode),location:{city:clean(body.location?.city),state:clean(body.location?.state),country:clean(body.location?.country)||'India'},salary:{min:body.salary?.min===''||body.salary?.min==null?0:Number(body.salary.min),max:body.salary?.max===''||body.salary?.max==null?0:Number(body.salary.max),currency:'INR',period:clean(body.salary?.period)||'year'},applicationDeadline:parseDate(body.applicationDeadline)};}
function validateJobPayload(payload,rawBody){const errors={title:required(payload.title,'Job title',2,120),category:required(payload.category,'Category',2,80),experience:required(payload.experience,'Experience',1,80),description:required(payload.description,'Job description',20,6000),'location.city':required(payload.location.city,'City',2,100),'location.state':required(payload.location.state,'State',2,100),summary:payload.summary.length>500?'Short summary must be 500 characters or fewer.':'',employmentType:!employmentTypes.includes(payload.employmentType)?'Select a valid employment type.':'',workMode:!workModes.includes(payload.workMode)?'Select a valid work mode.':'','salary.min':!Number.isFinite(payload.salary.min)||payload.salary.min<0?'Minimum salary must be a valid non-negative amount.':'','salary.max':!Number.isFinite(payload.salary.max)||payload.salary.max<0?'Maximum salary must be a valid non-negative amount.':payload.salary.min>0&&payload.salary.max>0&&payload.salary.max<payload.salary.min?'Maximum salary must be greater than or equal to minimum salary.':'','salary.period':!salaryPeriods.includes(payload.salary.period)?'Select a valid salary period.':'',applicationDeadline:rawBody.applicationDeadline&&!payload.applicationDeadline?'Enter a valid application deadline.':payload.applicationDeadline&&payload.applicationDeadline<=new Date()?'Application deadline must be in the future.':''};for(const [key,value] of Object.entries(errors))if(!value)delete errors[key];return errors;}
export async function createJob(req,res){const company=await getCompany(req.user._id);if(!company)return res.status(400).json({message:'Complete your company profile before creating jobs.'});const payload=jobPayload(req.body);const errors=validateJobPayload(payload,req.body);if(Object.keys(errors).length)return validationError(res,errors);let slug=slugify(payload.title)||`job-${Date.now()}`;if(await Job.exists({slug}))slug=`${slug}-${Date.now().toString().slice(-6)}`;const job=await Job.create({...payload,slug,company:company._id,createdBy:req.user._id,status:'draft'});return res.status(201).json({message:'Job created as draft.',job});}
export async function updateJob(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});const payload=jobPayload(req.body);const errors=validateJobPayload(payload,req.body);if(Object.keys(errors).length)return validationError(res,errors);Object.assign(job,payload);await job.save();return res.json({message:'Job updated.',job});}
export async function changeJobStatus(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});const next=req.body.status;if(!['draft','published','reviewing','paused','closed'].includes(next))return res.status(400).json({message:'Invalid job status.'});if(next==='published'){const company=await Company.findOne({_id:job.company,owner:req.user._id}).select('verificationStatus').lean();if(!company||company.verificationStatus!=='verified')return res.status(403).json({message:'Your company must be verified before a job can be published.'});if(job.applicationDeadline&&job.applicationDeadline<=new Date())return res.status(400).json({message:'Set a future application deadline before reopening applications.'});}const previous=job.status;if(previous===next)return res.status(409).json({message:`This job is already ${next}.`});job.status=next;if(next==='published'&&!job.publishedAt)job.publishedAt=new Date();job.closedAt=next==='closed'?new Date():null;await job.save();if(next==='published'&&previous!=='published')notifyMatchingJobAlerts(job).catch((error)=>console.error('Job alert notification matching failed:',error.message));const labels={draft:'saved as draft',published:'open for applications',reviewing:'moved to applicant review',paused:'paused',closed:'permanently closed'};return res.json({message:`Job ${labels[next]||next}.`,job});}
export async function deleteJob(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});if(await Application.exists({job:job._id}))return res.status(409).json({message:'Jobs with applications cannot be deleted. Close the role instead.'});await job.deleteOne();return res.json({message:'Job deleted.'});}
export async function listApplicants(req,res){const jobs=await Job.find({createdBy:req.user._id}).select('_id title slug').lean();const ids=jobs.map((job)=>job._id);const filter={job:{$in:ids}};if(req.query.status)filter.status=req.query.status;if(req.query.job)filter.job=req.query.job;const applications=await Application.find(filter).sort({createdAt:-1}).populate('candidate','firstName lastName email').lean();const profiles=await CandidateProfile.find({user:{$in:applications.map((item)=>item.candidate?._id).filter(Boolean)}}).lean();const profileMap=new Map(profiles.map((profile)=>[String(profile.user),profile]));return res.json({jobs,applications:applications.map((item)=>({...item,candidateProfile:profileMap.get(String(item.candidate?._id))||null}))});}
const statusLabels={reviewing:'Under review',shortlisted:'Shortlisted',interview:'Interview',offered:'Offer',hired:'Hired',rejected:'Not selected'};
const applicationTransitions={applied:['reviewing','shortlisted','rejected'],reviewing:['shortlisted','interview','rejected'],shortlisted:['interview','offered','rejected'],interview:['offered','rejected'],offered:['hired','rejected'],hired:[],rejected:[],withdrawn:[]};
export async function updateApplicationStatus(req,res){const application=await Application.findById(req.params.id).populate('candidate','firstName lastName email');if(!application)return res.status(404).json({message:'Application not found.'});const job=await ownedJob(req.user._id,application.job);if(!job)return res.status(403).json({message:'You cannot manage this application.'});const status=clean(req.body.status);if(!Object.prototype.hasOwnProperty.call(statusLabels,status))return res.status(400).json({message:'Invalid application status.'});const current=application.status;const allowed=applicationTransitions[current]||[];if(['hired','rejected','withdrawn'].includes(current))return res.status(409).json({message:`This application is ${current} and can no longer be moved through the recruiter pipeline.`});if(status===current)return res.status(409).json({message:'The application is already at this status.'});if(!allowed.includes(status))return res.status(409).json({message:`Cannot move an application from ${statusLabels[current]||current} directly to ${statusLabels[status]||status}. Follow the candidate pipeline in order.`,allowedStatuses:allowed});const note=clean(req.body.note);if(note.length>500)return validationError(res,{note:'Candidate note must be 500 characters or fewer.'});if(status==='rejected'&&note.length<5)return validationError(res,{note:'Add a short reason before rejecting this application.'});application.status=status;application.statusHistory.push({status,note,changedBy:req.user._id});await application.save();if(status==='hired')await ensureSuccessFeeForHire({application,job,recruiterId:req.user._id});const company=await Company.findById(job.company).lean();const label=statusLabels[status]||status;await createNotification({user:application.candidate._id,type:'application_status',title:`Application ${label.toLowerCase()}`,message:`Your application for ${job.title} at ${company?.name||'the employer'} is now ${label}.${note?` ${note}`:''}`,link:'/candidate/applications',metadata:{applicationId:application._id,jobId:job._id,status}});try{await sendEmail({to:application.candidate.email,subject:`Application update: ${job.title}`,html:brandedEmail({eyebrow:'Application update',title:`Your application is now ${label.toLowerCase()}`,greeting:`Hello ${application.candidate.firstName},`,paragraphs:[`There is an update to your application for ${job.title} at ${company?.name||'the employer'}.`,`Current status: ${label}.${note?` Recruiter note: ${note}`:''}`],buttonLabel:'View applications',buttonUrl:`${process.env.CLIENT_URL}/candidate/applications`,note:'You can track the full status history from your candidate workspace.'}),text:`Your application for ${job.title} is now ${label}.${note?` Note: ${note}`:''}`});}catch(error){console.error('Candidate status email failed:',error.message);}return res.json({message:'Application status updated.',application});}
export async function getSettings(req,res){return res.json({user:{firstName:req.user.firstName,lastName:req.user.lastName,email:req.user.email}});}
export async function updateSettings(req,res){const firstName=clean(req.body.firstName).slice(0,60),lastName=clean(req.body.lastName).slice(0,60);const errors={firstName:required(firstName,'First name',2,60),lastName:required(lastName,'Last name',2,60)};for(const key of Object.keys(errors))if(!errors[key])delete errors[key];if(Object.keys(errors).length)return validationError(res,errors);const user=await User.findByIdAndUpdate(req.user._id,{$set:{firstName,lastName}},{new:true,runValidators:true});return res.json({message:'Recruiter account updated.',user:{firstName:user.firstName,lastName:user.lastName,email:user.email}});}
