import Application from '../models/Application.js';
import CandidateProfile from '../models/CandidateProfile.js';
import Interview from '../models/Interview.js';
import TalentPool from '../models/TalentPool.js';
import { brandedEmail, sendEmail } from '../services/emailService.js';
import { createNotification } from '../services/notificationService.js';

const clean=(value='')=>String(value).trim();

export async function listTalentPools(req,res){const pools=await TalentPool.find({recruiter:req.user._id}).sort({updatedAt:-1}).populate('candidates.candidate','firstName lastName email').lean();return res.json({pools});}
export async function createTalentPool(req,res){const name=clean(req.body.name);if(name.length<2)return res.status(400).json({message:'Talent pool name is required.'});try{const pool=await TalentPool.create({recruiter:req.user._id,name,description:clean(req.body.description)});return res.status(201).json({message:'Talent pool created.',pool});}catch(error){if(error?.code===11000)return res.status(409).json({message:'You already have a talent pool with this name.'});throw error;}}
export async function deleteTalentPool(req,res){const pool=await TalentPool.findOneAndDelete({_id:req.params.id,recruiter:req.user._id});if(!pool)return res.status(404).json({message:'Talent pool not found.'});return res.json({message:'Talent pool deleted.'});}
export async function addCandidateToPool(req,res){const candidateId=String(req.body.candidateId||'');const profile=await CandidateProfile.findOne({user:candidateId,'privacy.discoverableToRecruiters':{$ne:false}});if(!profile)return res.status(404).json({message:'Candidate is not available for recruiter discovery.'});const pool=await TalentPool.findOne({_id:req.params.id,recruiter:req.user._id});if(!pool)return res.status(404).json({message:'Talent pool not found.'});const existing=pool.candidates.find((item)=>String(item.candidate)===candidateId);if(existing)existing.note=clean(req.body.note);else pool.candidates.push({candidate:candidateId,note:clean(req.body.note)});await pool.save();return res.json({message:'Candidate added to talent pool.',pool});}
export async function removeCandidateFromPool(req,res){const pool=await TalentPool.findOne({_id:req.params.id,recruiter:req.user._id});if(!pool)return res.status(404).json({message:'Talent pool not found.'});pool.candidates=pool.candidates.filter((item)=>String(item.candidate)!==String(req.params.candidateId));await pool.save();return res.json({message:'Candidate removed from talent pool.',pool});}

export async function listRecruiterInterviews(req,res){const interviews=await Interview.find({recruiter:req.user._id}).sort({scheduledAt:1}).populate('candidate','firstName lastName email').populate('job','title slug').lean();return res.json({interviews});}
export async function scheduleInterview(req,res){
  const application=await Application.findById(req.body.applicationId).populate('candidate','firstName lastName email').populate('job');if(!application||!application.job||String(application.job.createdBy)!==String(req.user._id))return res.status(404).json({message:'Application not found.'});
  if(['rejected','withdrawn','hired'].includes(application.status))return res.status(400).json({message:'This application cannot be scheduled for an interview.'});
  const scheduledAt=new Date(req.body.scheduledAt);if(Number.isNaN(scheduledAt.getTime())||scheduledAt<=new Date())return res.status(400).json({message:'Choose a future interview date and time.'});const mode=req.body.mode;if(!['video','phone','in-person'].includes(mode))return res.status(400).json({message:'Choose a valid interview mode.'});
  let interview=await Interview.findOne({application:application._id,status:{$in:['scheduled','confirmed']}});const payload={job:application.job._id,recruiter:req.user._id,candidate:application.candidate._id,scheduledAt,durationMinutes:Number(req.body.durationMinutes)||45,mode,meetingUrl:clean(req.body.meetingUrl),location:clean(req.body.location),instructions:clean(req.body.instructions),status:'scheduled',candidateResponse:'pending'};
  if(interview){Object.assign(interview,payload);await interview.save();}else interview=await Interview.create({application:application._id,...payload});
  if(application.status!=='interview'){application.status='interview';application.statusHistory.push({status:'interview',note:'Interview scheduled.',changedBy:req.user._id});await application.save();}
  const when=scheduledAt.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});await createNotification({user:application.candidate._id,type:'interview',title:`Interview scheduled for ${application.job.title}`,message:`Your interview is scheduled for ${when}.`,link:'/candidate/interviews',metadata:{interviewId:interview._id,applicationId:application._id}});
  try{await sendEmail({to:application.candidate.email,subject:`Interview scheduled: ${application.job.title}`,html:brandedEmail({eyebrow:'Interview invitation',title:'Your interview has been scheduled',greeting:`Hello ${application.candidate.firstName},`,paragraphs:[`Your interview for ${application.job.title} is scheduled for ${when}.`,`Interview mode: ${mode}.${payload.instructions?` ${payload.instructions}`:''}`],buttonLabel:'View interview',buttonUrl:`${process.env.CLIENT_URL}/candidate/interviews`,note:'Open your candidate workspace to accept or decline this interview invitation.'}),text:`Interview for ${application.job.title}: ${when}. Mode: ${mode}.`});}catch(error){console.error('Interview email failed:',error.message);}
  return res.status(201).json({message:'Interview scheduled.',interview});
}
export async function updateInterview(req,res){const interview=await Interview.findOne({_id:req.params.id,recruiter:req.user._id}).populate('candidate','firstName lastName email').populate('job','title');if(!interview)return res.status(404).json({message:'Interview not found.'});if(req.body.scheduledAt){const date=new Date(req.body.scheduledAt);if(Number.isNaN(date.getTime())||date<=new Date())return res.status(400).json({message:'Choose a future interview date and time.'});interview.scheduledAt=date;interview.candidateResponse='pending';}if(req.body.status&&['scheduled','completed','cancelled'].includes(req.body.status))interview.status=req.body.status;if(req.body.mode&&['video','phone','in-person'].includes(req.body.mode))interview.mode=req.body.mode;if(req.body.meetingUrl!==undefined)interview.meetingUrl=clean(req.body.meetingUrl);if(req.body.location!==undefined)interview.location=clean(req.body.location);if(req.body.instructions!==undefined)interview.instructions=clean(req.body.instructions);if(req.body.recruiterNotes!==undefined)interview.recruiterNotes=clean(req.body.recruiterNotes);await interview.save();await createNotification({user:interview.candidate._id,type:'interview',title:`Interview ${interview.status==='cancelled'?'cancelled':'updated'}`,message:`There is an update to your interview for ${interview.job?.title||'a role'}.`,link:'/candidate/interviews',metadata:{interviewId:interview._id}});return res.json({message:'Interview updated.',interview});}

export async function listCandidateInterviews(req,res){const interviews=await Interview.find({candidate:req.user._id}).sort({scheduledAt:1}).populate('recruiter','firstName lastName email').populate('job','title slug').lean();return res.json({interviews});}
export async function respondToInterview(req,res){const response=req.body.response;if(!['accepted','declined'].includes(response))return res.status(400).json({message:'Choose accept or decline.'});const interview=await Interview.findOne({_id:req.params.id,candidate:req.user._id}).populate('job','title');if(!interview||interview.status==='cancelled')return res.status(404).json({message:'Interview not found or no longer active.'});interview.candidateResponse=response;if(response==='accepted')interview.status='confirmed';await interview.save();await createNotification({user:interview.recruiter,type:'interview_response',title:`Interview ${response}`,message:`${req.user.firstName} ${req.user.lastName} ${response} the interview for ${interview.job?.title||'the role'}.`,link:'/recruiter/interviews',metadata:{interviewId:interview._id}});return res.json({message:`Interview ${response}.`,interview});}
