import Application from '../models/Application.js';
import CandidateProfile from '../models/CandidateProfile.js';
import Company from '../models/Company.js';
import Job from '../models/Job.js';
import User from '../models/User.js';
import { brandedEmail, sendEmail } from '../services/emailService.js';
import { createNotification, notifyMatchingJobAlerts } from '../services/notificationService.js';
import { ensureSuccessFeeForHire } from '../services/successFeeService.js';

const clean=(value='')=>String(value).trim();
const list=(value,max=30)=>Array.isArray(value)?value.map((item)=>clean(item)).filter(Boolean).slice(0,max):[];
const slugify=(value)=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,120);
const parseDate=(value)=>{if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};
async function getCompany(userId){return Company.findOne({owner:userId});}async function ownedJob(userId,id){return Job.findOne({_id:id,createdBy:userId});}
export async function getOverview(req,res){const company=await getCompany(req.user._id);if(!company)return res.json({company:null,counts:{jobs:0,publishedJobs:0,applications:0,interviews:0,offers:0},recentApplications:[]});const jobIds=await Job.find({createdBy:req.user._id}).distinct('_id');const [jobs,publishedJobs,applications,interviews,offers,recentApplications]=await Promise.all([Job.countDocuments({createdBy:req.user._id}),Job.countDocuments({createdBy:req.user._id,status:'published'}),Application.countDocuments({job:{$in:jobIds}}),Application.countDocuments({job:{$in:jobIds},status:'interview'}),Application.countDocuments({job:{$in:jobIds},status:'offered'}),Application.find({job:{$in:jobIds}}).sort({updatedAt:-1}).limit(6).populate('candidate','firstName lastName email').lean()]);return res.json({company,counts:{jobs,publishedJobs,applications,interviews,offers},recentApplications});}
export async function getCompanyProfile(req,res){return res.json({company:await getCompany(req.user._id)});}export async function saveCompanyProfile(req,res){const name=clean(req.body.name);if(name.length<2)return res.status(400).json({message:'Company name is required.'});let company=await getCompany(req.user._id);const payload={name,website:clean(req.body.website),industry:clean(req.body.industry),size:clean(req.body.size),location:clean(req.body.location),description:clean(req.body.description),logoUrl:clean(req.body.logoUrl),verificationStatus:'verified'};if(company){Object.assign(company,payload);await company.save();}else{let slug=slugify(name)||`company-${Date.now()}`;if(await Company.exists({slug}))slug=`${slug}-${String(req.user._id).slice(-6)}`;company=await Company.create({...payload,slug,owner:req.user._id});}return res.json({message:'Company profile saved.',company});}
export async function listJobs(req,res){const jobs=await Job.find({createdBy:req.user._id}).sort({createdAt:-1}).lean();const ids=jobs.map((job)=>job._id);const counts=await Application.aggregate([{$match:{job:{$in:ids}}},{$group:{_id:'$job',count:{$sum:1}}}]);const map=new Map(counts.map((item)=>[String(item._id),item.count]));return res.json({jobs:jobs.map((job)=>({...job,applicants:map.get(String(job._id))||0}))});}
function jobPayload(body){return {title:clean(body.title),summary:clean(body.summary),description:clean(body.description),category:clean(body.category)||'Other',experience:clean(body.experience),responsibilities:list(body.responsibilities),requirements:list(body.requirements),benefits:list(body.benefits),skills:list(body.skills,40),employmentType:body.employmentType,workMode:body.workMode,location:{city:clean(body.location?.city),state:clean(body.location?.state),country:clean(body.location?.country)||'India'},salary:{min:Number(body.salary?.min)||0,max:Number(body.salary?.max)||0,currency:'INR',period:body.salary?.period||'year'},applicationDeadline:parseDate(body.applicationDeadline)};}
export async function createJob(req,res){const company=await getCompany(req.user._id);if(!company)return res.status(400).json({message:'Complete your company profile before creating jobs.'});const payload=jobPayload(req.body);if(!payload.title||!payload.description||!payload.employmentType||!payload.workMode)return res.status(400).json({message:'Title, description, employment type, and work mode are required.'});let slug=slugify(payload.title)||`job-${Date.now()}`;if(await Job.exists({slug}))slug=`${slug}-${Date.now().toString().slice(-6)}`;const job=await Job.create({...payload,slug,company:company._id,createdBy:req.user._id,status:'draft'});return res.status(201).json({message:'Job created as draft.',job});}
export async function updateJob(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});Object.assign(job,jobPayload(req.body));await job.save();return res.json({message:'Job updated.',job});}
export async function changeJobStatus(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});const next=req.body.status;if(!['draft','published','reviewing','paused','closed'].includes(next))return res.status(400).json({message:'Invalid job status.'});if(next==='published'&&job.applicationDeadline&&job.applicationDeadline<=new Date())return res.status(400).json({message:'Set a future application deadline before reopening applications.'});const previous=job.status;job.status=next;if(next==='published'&&!job.publishedAt)job.publishedAt=new Date();job.closedAt=next==='closed'?new Date():null;await job.save();if(next==='published'&&previous!=='published')notifyMatchingJobAlerts(job).catch((error)=>console.error('Job alert notification matching failed:',error.message));const labels={draft:'saved as draft',published:'open for applications',reviewing:'moved to applicant review',paused:'paused',closed:'permanently closed'};return res.json({message:`Job ${labels[next]||next}.`,job});}
export async function deleteJob(req,res){const job=await ownedJob(req.user._id,req.params.id);if(!job)return res.status(404).json({message:'Job not found.'});if(await Application.exists({job:job._id}))return res.status(409).json({message:'Jobs with applications cannot be deleted. Close the role instead.'});await job.deleteOne();return res.json({message:'Job deleted.'});}
export async function listApplicants(req,res){const jobs=await Job.find({createdBy:req.user._id}).select('_id title slug').lean();const ids=jobs.map((job)=>job._id);const filter={job:{$in:ids}};if(req.query.status)filter.status=req.query.status;if(req.query.job)filter.job=req.query.job;const applications=await Application.find(filter).sort({createdAt:-1}).populate('candidate','firstName lastName email').lean();const profiles=await CandidateProfile.find({user:{$in:applications.map((item)=>item.candidate?._id).filter(Boolean)}}).lean();const profileMap=new Map(profiles.map((profile)=>[String(profile.user),profile]));return res.json({jobs,applications:applications.map((item)=>({...item,candidateProfile:profileMap.get(String(item.candidate?._id))||null}))});}
const statusLabels={reviewing:'Under review',shortlisted:'Shortlisted',interview:'Interview',offered:'Offer',hired:'Hired',rejected:'Not selected'};
export async function updateApplicationStatus(req,res){const application=await Application.findById(req.params.id).populate('candidate','firstName lastName email');if(!application)return res.status(404).json({message:'Application not found.'});const job=await ownedJob(req.user._id,application.job);if(!job)return res.status(403).json({message:'You cannot manage this application.'});const status=req.body.status;if(!['reviewing','shortlisted','interview','offered','hired','rejected'].includes(status))return res.status(400).json({message:'Invalid application status.'});const note=clean(req.body.note).slice(0,500);application.status=status;application.statusHistory.push({status,note,changedBy:req.user._id});await application.save();if(status==='hired')await ensureSuccessFeeForHire({application,job,recruiterId:req.user._id});const company=await Company.findById(job.company).lean();const label=statusLabels[status]||status;await createNotification({user:application.candidate._id,type:'application_status',title:`Application ${label.toLowerCase()}`,message:`Your application for ${job.title} at ${company?.name||'the employer'} is now ${label}.${note?` ${note}`:''}`,link:'/candidate/applications',metadata:{applicationId:application._id,jobId:job._id,status}});try{await sendEmail({to:application.candidate.email,subject:`Application update: ${job.title}`,html:brandedEmail({eyebrow:'Application update',title:`Your application is now ${label.toLowerCase()}`,greeting:`Hello ${application.candidate.firstName},`,paragraphs:[`There is an update to your application for ${job.title} at ${company?.name||'the employer'}.`,`Current status: ${label}.${note?` Recruiter note: ${note}`:''}`],buttonLabel:'View applications',buttonUrl:`${process.env.CLIENT_URL}/candidate/applications`,note:'You can track the full status history from your candidate workspace.'}),text:`Your application for ${job.title} is now ${label}.${note?` Note: ${note}`:''}`});}catch(error){console.error('Candidate status email failed:',error.message);}return res.json({message:'Application status updated.',application});}
export async function getSettings(req,res){return res.json({user:{firstName:req.user.firstName,lastName:req.user.lastName,email:req.user.email}});}export async function updateSettings(req,res){const firstName=clean(req.body.firstName),lastName=clean(req.body.lastName);if(firstName.length<2||lastName.length<2)return res.status(400).json({message:'First and last name must be at least 2 characters.'});const user=await User.findByIdAndUpdate(req.user._id,{$set:{firstName,lastName}},{new:true,runValidators:true});return res.json({message:'Recruiter account updated.',user:{firstName:user.firstName,lastName:user.lastName,email:user.email}});}
