import mongoose from 'mongoose';import Conversation from '../models/Conversation.js';import Job from '../models/Job.js';import Company from '../models/Company.js';import Message from '../models/Message.js';import SafetyReport from '../models/SafetyReport.js';import UserBlock from '../models/UserBlock.js';
const reasons=new Set(['spam','harassment','scam','impersonation','inappropriate_content','misleading_job','privacy','other']);
async function resolveTarget(user,type,id){if(!mongoose.isValidObjectId(id))return null;if(type==='conversation'){const item=await Conversation.findOne({_id:id,$or:[{candidate:user._id},{recruiter:user._id}]});if(!item)return null;return {target:item,reportedUser:String(item.candidate)===String(user._id)?item.recruiter:item.candidate};}if(type==='message'){const item=await Message.findById(id);if(!item)return null;const convo=await Conversation.findOne({_id:item.conversation,$or:[{candidate:user._id},{recruiter:user._id}]});if(!convo)return null;return {target:item,reportedUser:item.sender};}if(type==='job'){const item=await Job.findById(id).populate('createdBy');return item?{target:item,reportedUser:item.createdBy?._id||item.createdBy}:null;}if(type==='company'){const item=await Company.findById(id);return item?{target:item,reportedUser:item.createdBy||null}:null;}return null;}
export async function listBlocks(req,res){const blocks=await UserBlock.find({blocker:req.user._id}).populate('blocked','firstName lastName role').sort({createdAt:-1}).lean();return res.json({blocks});}
export async function blockUser(req,res){const id=String(req.params.userId||'');if(!mongoose.isValidObjectId(id)||id===String(req.user._id))return res.status(400).json({message:'Invalid user to block.'});const conversation=await Conversation.findOne({$or:[{candidate:req.user._id,recruiter:id},{candidate:id,recruiter:req.user._id}]});if(!conversation)return res.status(403).json({message:'You can only block a candidate or recruiter you have interacted with.'});await UserBlock.findOneAndUpdate({blocker:req.user._id,blocked:id},{$set:{reason:String(req.body.reason||'').trim().slice(0,500)}},{upsert:true,new:true,setDefaultsOnInsert:true});return res.json({message:'User blocked. They can no longer message you.'});}
export async function unblockUser(req,res){await UserBlock.deleteOne({blocker:req.user._id,blocked:req.params.userId});return res.json({message:'User unblocked.'});}
export async function createReport(req,res){const type=String(req.body.targetType||'');const id=String(req.body.targetId||'');const reason=String(req.body.reason||'other');if(!['conversation','message','job','company'].includes(type)||!reasons.has(reason))return res.status(400).json({message:'Choose a valid report target and reason.'});const resolved=await resolveTarget(req.user,type,id);if(!resolved)return res.status(404).json({message:'The reported item could not be found or accessed.'});const duplicate=await SafetyReport.findOne({reporter:req.user._id,targetType:type,targetId:id,status:{$in:['open','reviewing']}});if(duplicate)return res.status(409).json({message:'You already have an active report for this item.'});const report=await SafetyReport.create({reporter:req.user._id,reportedUser:resolved.reportedUser||null,targetType:type,targetId:id,reason,details:String(req.body.details||'').trim().slice(0,2000)});return res.status(201).json({message:'Report submitted for review.',report});}
export async function listMyReports(req,res){const reports=await SafetyReport.find({reporter:req.user._id}).sort({createdAt:-1}).lean();return res.json({reports});}
export async function listReports(req,res){const status=String(req.query.status||'');const filter=status&&['open','reviewing','resolved','dismissed'].includes(status)?{status}:{};const reports=await SafetyReport.find(filter).populate('reporter','firstName lastName email role').populate('reportedUser','firstName lastName email role status').populate('reviewedBy','firstName lastName').sort({createdAt:-1}).limit(250).lean();return res.json({reports});}
export async function reviewReport(req,res){const status=String(req.body.status||'');if(!['reviewing','resolved','dismissed'].includes(status))return res.status(400).json({message:'Choose a valid moderation status.'});const report=await SafetyReport.findByIdAndUpdate(req.params.id,{$set:{status,resolution:String(req.body.resolution||'').trim().slice(0,2000),reviewedBy:req.user._id,reviewedAt:new Date()}},{new:true,runValidators:true});if(!report)return res.status(404).json({message:'Report not found.'});return res.json({message:'Moderation report updated.',report});}
