import { Activity, BarChart3, BriefcaseBusiness, FileCheck2, UsersRound } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../lib/api.js';

export default function AdminAnalyticsPage(){
  const [data,setData]=useState(null);const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false;apiRequest('/admin/analytics').then(r=>!cancelled&&setData(r)).catch(e=>!cancelled&&setError(e.message));return()=>{cancelled=true;};},[]);
  const summary=useMemo(()=>{if(!data)return null;const total=(rows=[])=>rows.reduce((sum,row)=>sum+Number(row.count||0),0);return {users:total(data.usersByRole),applications:total(data.applicationsByStatus),jobs:total(data.jobsByStatus),registrations:total(data.registrations)};},[data]);
  if(!data)return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">{error||'Loading analytics…'}</div>;
  return <section className="space-y-6"><div className="rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#879E83]"><BarChart3 size={22}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#F3E8A2]">Platform analytics</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Understand marketplace growth and hiring activity.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Use live platform aggregates to understand account growth, job inventory and application outcomes. These figures describe platform activity rather than guaranteed hiring performance.</p></div></div><Link to="/admin/activity" className="inline-flex items-center gap-2 self-start rounded-xl border border-white/15 px-4 py-2.5 text-xs font-semibold text-white transition hover:-translate-y-0.5 hover:bg-white/10 lg:self-auto"><Activity size={15}/> Audit activity</Link></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={UsersRound} label="Accounts represented" value={summary.users}/><Summary icon={BriefcaseBusiness} label="Jobs represented" value={summary.jobs}/><Summary icon={FileCheck2} label="Applications represented" value={summary.applications}/><Summary icon={Activity} label="Registrations in trend" value={summary.registrations}/></div><div className="grid gap-6 xl:grid-cols-3"><Metric title="Users by role" description="Current account distribution across platform roles." rows={data.usersByRole}/><Metric title="Applications by status" description="Current candidate progression across application states." rows={data.applicationsByStatus}/><Metric title="Jobs by status" description="Current role inventory across its publishing lifecycle." rows={data.jobsByStatus}/></div><RegistrationTrend rows={data.registrations}/></section>;
}
function Summary({icon:Icon,label,value}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><span className="grid size-10 place-items-center rounded-xl bg-[#F3E8A2]/65 text-indigo-700"><Icon size={18}/></span><strong className="mt-5 block text-2xl text-slate-950">{value}</strong><span className="mt-1 block text-sm text-slate-500">{label}</span></article>}
function Metric({title,description,rows=[]}){return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:border-slate-300 hover:shadow-md"><h3 className="font-semibold text-slate-950">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p><div className="mt-4 space-y-3">{rows.length?rows.map(r=><div key={r._id||'unspecified'} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 transition hover:bg-indigo-50/60"><span className="text-sm capitalize text-slate-600">{String(r._id||'unspecified').replaceAll('_',' ')}</span><strong className="text-sm text-slate-950">{r.count}</strong></div>):<p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-400">No data available yet.</p>}</div></section>}
function RegistrationTrend({rows=[]}){const max=Math.max(...rows.map(x=>Number(x.count||0)),1);return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><h3 className="text-lg font-semibold text-slate-950">Registration trend</h3><p className="mt-1 text-sm leading-6 text-slate-500">Account registrations returned by the analytics service for the current reporting window.</p></div>{rows.length?<div className="mt-7 flex min-h-64 items-end gap-3 overflow-x-auto pb-1">{rows.map(r=><div key={r._id} className="group flex min-w-16 flex-1 flex-col items-center gap-2"><span className="text-xs font-semibold text-slate-600">{r.count}</span><div className="w-full rounded-t-xl bg-[#879E83] transition duration-300 group-hover:bg-indigo-500" style={{height:`${Math.max(16,(Number(r.count||0)/max)*176)}px`}}/><span className="whitespace-nowrap text-[10px] text-slate-400">{r._id}</span></div>)}</div>:<p className="mt-6 rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">Registration trend data will appear here when activity is available.</p>}</section>}
