import { BellRing, Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import ActionModal from '../../components/ActionModal.jsx';
import { apiRequest } from '../../lib/api.js';

const empty={name:'',keywords:'',location:'',category:'',workMode:'',employmentType:'',frequency:'instant',emailEnabled:true,inAppEnabled:true,active:true};
export default function CandidateJobAlertsPage(){
  const [alerts,setAlerts]=useState(null);const [form,setForm]=useState(empty);const [open,setOpen]=useState(false);const [editing,setEditing]=useState('');const [message,setMessage]=useState('');const [removeTarget,setRemoveTarget]=useState(null);
  const load=async()=>{try{const r=await apiRequest('/candidate/job-alerts');setAlerts(r.alerts||[]);}catch(e){setMessage(e.message);}};
  useEffect(()=>{let cancelled=false;apiRequest('/candidate/job-alerts').then((r)=>!cancelled&&setAlerts(r.alerts||[])).catch((e)=>!cancelled&&setMessage(e.message));return()=>{cancelled=true;};},[]);
  const edit=(alert)=>{setEditing(alert._id);setForm({...empty,...alert,frequency:'instant'});setOpen(true);};
  const save=async(e)=>{e.preventDefault();try{const r=await apiRequest(editing?`/candidate/job-alerts/${editing}`:'/candidate/job-alerts',{method:editing?'PUT':'POST',body:JSON.stringify({...form,frequency:'instant'})});setMessage(r.message);setForm(empty);setEditing('');setOpen(false);await load();}catch(err){setMessage(err.message);}};
  const remove=async()=>{if(!removeTarget)return;try{const r=await apiRequest(`/candidate/job-alerts/${removeTarget._id}`,{method:'DELETE'});setMessage(r.message);setRemoveTarget(null);await load();}catch(err){setMessage(err.message);}};
  return <section className="space-y-6"><div className="rounded-[2rem] bg-[#879E83] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/80">Opportunity discovery</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-slate-950 sm:text-4xl">Job alerts</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-900/70">Save the kind of role you want and receive an instant in-app notification or branded email when a recruiter publishes a matching job.</p></div><button type="button" onClick={()=>{setEditing('');setForm(empty);setOpen(true);}} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white"><Plus size={16}/> Create alert</button></div></div>{message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}{open&&<AlertForm form={form} setForm={setForm} onSubmit={save} onClose={()=>setOpen(false)} editing={Boolean(editing)}/>}<div className="grid gap-4 lg:grid-cols-2">{!alerts?<State text="Loading job alerts…"/>:alerts.length?alerts.map((alert)=><article key={alert._id} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#F3E8A2]/70 text-indigo-700"><BellRing size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{alert.name}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${alert.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{alert.active?'Active':'Paused'}</span></div><p className="mt-2 text-sm text-slate-600">{[alert.keywords,alert.location,alert.category,alert.workMode,alert.employmentType].filter(Boolean).join(' · ')||'Broad matching'}</p><p className="mt-2 text-xs text-slate-400">Instant · {alert.inAppEnabled?'In-app on':'In-app off'} · {alert.emailEnabled?'Email on':'Email off'}</p><div className="mt-4 flex gap-2"><button type="button" onClick={()=>edit(alert)} className="rounded-xl border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-700">Edit</button><button type="button" onClick={()=>setRemoveTarget(alert)} className="grid size-9 place-items-center rounded-xl border border-red-200 text-red-600"><Trash2 size={15}/></button></div></div></div></article>):<State text="No job alerts yet. Create one to start matching new roles."/>}</div><ActionModal open={Boolean(removeTarget)} title="Delete this job alert?" description="You will stop receiving matches for this alert." confirmLabel="Delete alert" tone="danger" onClose={()=>setRemoveTarget(null)} onConfirm={remove}/></section>;
}
function AlertForm({form,setForm,onSubmit,onClose,editing}){const input='w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-amber-400 focus:ring-4 focus:ring-amber-100';const set=(key,value)=>setForm((current)=>({...current,[key]:value}));return <form onSubmit={onSubmit} className="rounded-[1.7rem] border border-amber-200 bg-[#F3E8A2]/25 p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h3 className="text-xl font-semibold text-slate-950">{editing?'Edit job alert':'Create job alert'}</h3><p className="mt-1 text-sm text-slate-500">Use one or several conditions to define the opportunities you want. Matching alerts are sent instantly.</p></div><button type="button" onClick={onClose} className="text-sm font-semibold text-slate-500">Close</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Alert name"><input required value={form.name} onChange={(e)=>set('name',e.target.value)} className={input} placeholder="Frontend roles in Jodhpur"/></Field><Field label="Keywords"><input value={form.keywords} onChange={(e)=>set('keywords',e.target.value)} className={input} placeholder="React"/></Field><Field label="Location"><input value={form.location} onChange={(e)=>set('location',e.target.value)} className={input} placeholder="Jodhpur"/></Field><Field label="Category"><input value={form.category} onChange={(e)=>set('category',e.target.value)} className={input} placeholder="Engineering"/></Field><Field label="Work mode"><select value={form.workMode} onChange={(e)=>set('workMode',e.target.value)} className={input}><option value="">Any work mode</option><option value="on-site">On-site</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option></select></Field><Field label="Employment type"><select value={form.employmentType} onChange={(e)=>set('employmentType',e.target.value)} className={input}><option value="">Any type</option><option value="full-time">Full-time</option><option value="part-time">Part-time</option><option value="contract">Contract</option><option value="internship">Internship</option><option value="temporary">Temporary</option></select></Field></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Toggle label="Active" checked={form.active} onChange={(value)=>set('active',value)}/><Toggle label="In-app notifications" checked={form.inAppEnabled} onChange={(value)=>set('inAppEnabled',value)}/><Toggle label="Email alerts" checked={form.emailEnabled} onChange={(value)=>set('emailEnabled',value)}/></div><button className="mt-6 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{editing?'Save alert':'Create alert'}</button></form>}
function Toggle({label,checked,onChange}){return <label className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="size-4 accent-indigo-600"/></label>}
function Field({label,children}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-2 block">{label}</span>{children}</label>}
function State({text}){return <div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 lg:col-span-2">{text}</div>}
