import { Bookmark, BriefcaseBusiness, CalendarClock, ChevronRight, CreditCard, FileText, GraduationCap, Handshake, MessageSquare, Rocket, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../lib/api.js';

const statusLabel={applied:'Applied',reviewing:'Under review',shortlisted:'Shortlisted',interview:'Interview',offered:'Offer',hired:'Hired',rejected:'Rejected',withdrawn:'Withdrawn'};
const tools=[[CalendarClock,'Interviews','Keep upcoming interview activity and outcomes visible.','/candidate/interviews'],[MessageSquare,'Messages','Continue recruiter conversations without losing hiring context.','/candidate/messages'],[GraduationCap,'Career Programmes','Review programme enrollment, service milestones and progress.','/candidate/career-programs'],[Handshake,'Placements','Follow placement outcomes and related career activity.','/candidate/placements'],[CreditCard,'Billing & receipts','Review instalments, verified payments, receipts and eligible refunds.','/candidate/billing'],[Rocket,'Profile visibility','Manage eligible profile promotion and recruiter discoverability.','/candidate/promotions']];
export default function CandidateOverviewPage(){
  const [data,setData]=useState(null); const [recommended,setRecommended]=useState([]); const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false;Promise.all([apiRequest('/candidate/overview'),apiRequest('/candidate/recommended-jobs')]).then(([overview,recs])=>{if(!cancelled){setData(overview);setRecommended(recs.jobs||[]);}}).catch((err)=>!cancelled&&setError(err.message));return()=>{cancelled=true;};},[]);
  if(error)return <State text={error}/>; if(!data)return <State text="Loading your workspace…"/>;
  const cards=[[BriefcaseBusiness,'Active applications',data.counts.activeApplications],[Bookmark,'Saved jobs',data.counts.savedJobs],[CalendarClock,'Interviews',data.counts.interviews],[FileText,'Profile strength',`${data.profileCompletion}%`]];
  return <section className="space-y-8">
    <div className="rounded-[2rem] bg-[#879E83] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-white/80">Candidate workspace</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-semibold tracking-[-.04em] text-slate-950 sm:text-4xl">Keep your career activity connected.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-900/70">Discover opportunities, track applications and interviews, manage recruiter conversations, strengthen your profile and keep Career Programme, placement and billing activity in one workspace.</p></div><Link to="/jobs" className="group inline-flex shrink-0 items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-indigo-600 hover:shadow-lg">Browse jobs <ChevronRight size={16} className="transition-transform group-hover:translate-x-1"/></Link></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon,label,value])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-lg"><span className="grid size-10 place-items-center rounded-xl bg-[#F3E8A2]/70 text-indigo-700"><Icon size={19}/></span><strong className="mt-5 block text-2xl text-slate-950">{value}</strong><span className="mt-1 block text-sm text-slate-500">{label}</span></article>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
      <Card title="Recent applications" action="View all" to="/candidate/applications">{data.recentApplications.length?data.recentApplications.map((app)=><div key={app._id} className="flex items-center gap-4 border-t border-slate-100 py-4 first:border-0"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-slate-950 text-xs font-bold text-white">{app.jobSnapshot?.initials||'RB'}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-950">{app.jobSnapshot?.title}</strong><span className="text-xs text-slate-500">{app.jobSnapshot?.company}</span></div><span className="rounded-full bg-[#F3E8A2]/65 px-3 py-1 text-[11px] font-semibold text-slate-700">{statusLabel[app.status]||app.status}</span></div>):<Empty text="No applications yet. Start with a role that fits."/>}</Card>
      <Card title="Profile readiness" action="Complete profile" to="/candidate/profile"><div className="py-3"><div className="flex items-center justify-between text-sm"><span className="text-slate-500">Profile completion</span><strong>{data.profileCompletion}%</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#E3A341]" style={{width:`${data.profileCompletion}%`}}/></div><p className="mt-4 text-sm leading-6 text-slate-500">Add skills, work history, education, job preferences and your resume. Keep recruiter discoverability enabled when you want verified employers to find your profile.</p></div></Card>
    </div>
    <Card title="Recommended opportunities" action="Browse all jobs" to="/jobs"><div className="grid gap-3 md:grid-cols-2">{recommended.length?recommended.map((job)=><Link key={job.slug} to={`/jobs/${job.slug}`} className="rounded-2xl border border-slate-200 p-4 transition duration-300 hover:-translate-y-0.5 hover:border-amber-300 hover:bg-amber-50/20 hover:shadow-md"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#879E83] text-xs font-bold text-white">{job.initials}</span><div><strong className="text-sm text-slate-950">{job.title}</strong><p className="mt-1 text-xs text-slate-500">{job.company} · {job.workplace}</p></div></div></Link>):<Empty text="Complete your profile and preferences to improve recommendations."/>}</div></Card>
    <div><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-700">More from your workspace</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">Career tools beyond the application.</h3></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tools.map(([Icon,title,copy,to])=><Link key={title} to={to} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-lg"><span className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700 transition group-hover:bg-indigo-600 group-hover:text-white"><Icon size={18}/></span><strong className="mt-4 block text-sm text-slate-950">{title}</strong><p className="mt-1.5 text-xs leading-5 text-slate-500">{copy}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-indigo-700">Open <ChevronRight size={13} className="transition-transform group-hover:translate-x-1"/></span></Link>)}</div></div>
  </section>;
}
function Card({title,action,to,children}){return <article className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-3 flex items-center justify-between gap-4"><h3 className="text-lg font-semibold text-slate-950">{title}</h3><Link to={to} className="rounded-lg px-2 py-1 text-xs font-semibold text-indigo-700 transition hover:bg-indigo-50 hover:text-emerald-700">{action}</Link></div>{children}</article>}
function Empty({text}){return <div className="py-8 text-center text-sm text-slate-500"><Sparkles size={22} className="mx-auto mb-2 text-slate-300"/>{text}</div>}
function State({text}){return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">{text}</div>}
