import { BriefcaseBusiness, Clock3, FileCheck2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import ActionModal from '../../components/ActionModal.jsx';
import CustomSelect from '../../components/ui/CustomSelect.jsx';
import {FormField,FormTextarea} from '../../components/ui/FormField.jsx';
import { apiRequest } from '../../lib/api.js';

const labels={applied:'Applied',reviewing:'Under review',shortlisted:'Shortlisted',interview:'Interview',offered:'Offer',hired:'Hired',rejected:'Rejected',withdrawn:'Withdrawn'};
const statusStyles={applied:'bg-slate-100 text-slate-700',reviewing:'bg-blue-50 text-blue-700',shortlisted:'bg-[#F3E8A2]/70 text-amber-800',interview:'bg-violet-50 text-violet-700',offered:'bg-emerald-50 text-emerald-700',hired:'bg-emerald-100 text-emerald-800',rejected:'bg-red-50 text-red-700',withdrawn:'bg-slate-100 text-slate-500'};

export default function CandidateApplicationsPage(){
  const navigate=useNavigate();const [searchParams]=useSearchParams();const requestedJob=searchParams.get('job')||'';
  const [applications,setApplications]=useState(null);const [jobs,setJobs]=useState([]);const [hasResume,setHasResume]=useState(false);const [filter,setFilter]=useState('all');const [form,setForm]=useState({jobSlug:requestedJob,coverLetter:''});const [message,setMessage]=useState('');const [submitting,setSubmitting]=useState(false);const [showApply,setShowApply]=useState(Boolean(requestedJob));const [resumeModal,setResumeModal]=useState(false);const [withdrawTarget,setWithdrawTarget]=useState(null);const [withdrawing,setWithdrawing]=useState(false);
  useEffect(()=>{let cancelled=false;Promise.all([apiRequest('/candidate/applications'),apiRequest('/public/jobs'),apiRequest('/candidate/profile')]).then(([apps,jobsResponse,profileResponse])=>{if(!cancelled){setApplications(apps.applications||[]);setJobs(jobsResponse.jobs||[]);setHasResume(Boolean(profileResponse.profile?.resume?.url));}}).catch((e)=>!cancelled&&setMessage(e.message));return()=>{cancelled=true;};},[]);
  const visible=useMemo(()=>!applications?[]:filter==='all'?applications:applications.filter((item)=>item.status===filter),[applications,filter]);
  const appliedSlugs=useMemo(()=>new Set((applications||[]).map((item)=>item.jobSlug)),[applications]);
  const availableJobs=useMemo(()=>jobs.filter((job)=>job.acceptingApplications&&!appliedSlugs.has(job.slug)),[jobs,appliedSlugs]);
  const jobOptions=useMemo(()=>[{value:'',label:'Select an opportunity'},...availableJobs.map((job)=>({value:job.slug,label:`${job.title} — ${job.company}`}))],[availableJobs]);
  const apply=async(e)=>{e.preventDefault();if(!hasResume){setResumeModal(true);return;}if(!form.jobSlug){setMessage('Choose a job first.');return;}if(form.coverLetter.length>3000){setMessage('Cover note must be 3,000 characters or fewer.');return;}setSubmitting(true);setMessage('');try{const r=await apiRequest('/candidate/applications',{method:'POST',body:JSON.stringify(form)});setApplications((current)=>[r.application,...(current||[])]);setForm({jobSlug:'',coverLetter:''});setShowApply(false);setMessage(r.message);}catch(err){if(err.body?.code==='RESUME_REQUIRED'||/resume/i.test(err.message||'')){setHasResume(false);setResumeModal(true);}else setMessage(err.message);}finally{setSubmitting(false);}};
  const withdraw=async()=>{if(!withdrawTarget)return;setWithdrawing(true);try{const r=await apiRequest(`/candidate/applications/${withdrawTarget._id}/withdraw`,{method:'PATCH'});setApplications((current)=>current.map((item)=>item._id===withdrawTarget._id?r.application:item));setMessage(r.message);setWithdrawTarget(null);}catch(err){setMessage(err.message);}finally{setWithdrawing(false);}};
  if(!applications)return <State text={message||'Loading applications…'}/>;
  return <section className="space-y-6">
    <div className="rounded-[2rem] bg-[#879E83] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/80">Applications</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-slate-950 sm:text-4xl">Know where every application stands.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-900/70">Submit applications, review status history, and withdraw active applications when your plans change.</p></div><button type="button" onClick={()=>{if(!hasResume){setResumeModal(true);return;}setShowApply((v)=>!v);}} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{showApply?'Close form':'Apply to a role'}</button></div></div>
    {!hasResume&&<div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm text-amber-900"><strong>A resume is required to apply.</strong><span className="ml-1">Upload a current PDF before submitting any application.</span><button type="button" onClick={()=>navigate('/candidate/resume')} className="ml-2 font-semibold underline">Add resume</button></div>}
    {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
    {showApply&&<form onSubmit={apply} className="rounded-[1.8rem] border border-amber-200 bg-gradient-to-br from-[#FFF9DE] via-white to-amber-50/60 p-5 shadow-[0_18px_50px_rgba(120,53,15,0.08)] sm:p-6" noValidate><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700">New application</p><h3 className="mt-2 text-xl font-semibold text-slate-950">Send a focused application</h3><p className="mt-1 text-sm text-slate-500">Choose an active role and add a short, relevant note for the recruiter.</p></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><CustomSelect label="Choose job" value={form.jobSlug} onChange={(value)=>setForm({...form,jobSlug:value})} options={jobOptions}/><FormField label="Cover note" hint={`${form.coverLetter.length}/3000 characters`}><FormTextarea maxLength="3000" rows="5" value={form.coverLetter} onChange={(e)=>setForm({...form,coverLetter:e.target.value})} placeholder="Why are you interested in this role?"/></FormField></div><div className="mt-5 flex justify-end"><button disabled={submitting||!hasResume} className="rounded-2xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-amber-900/10 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50">{submitting?'Submitting…':'Submit application'}</button></div></form>}
    <div className="flex flex-wrap gap-2">{['all','applied','reviewing','shortlisted','interview','offered','hired','rejected','withdrawn'].map((item)=><button key={item} type="button" onClick={()=>setFilter(item)} className={`rounded-xl px-3.5 py-2 text-xs font-semibold capitalize ${filter===item?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{item==='reviewing'?'Under review':item}</button>)}</div>
    {visible.length?<div className="space-y-4">{visible.map((app)=><article key={app._id} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="flex min-w-0 items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-slate-950 text-sm font-bold text-white">{app.jobSnapshot?.initials||'RB'}</span><div className="min-w-0"><p className="text-xs font-medium text-slate-500">{app.jobSnapshot?.company}</p><h3 className="mt-1 text-lg font-semibold text-slate-950">{app.jobSnapshot?.title}</h3><p className="mt-2 text-xs text-slate-500">{app.jobSnapshot?.location} · {app.jobSnapshot?.workplace} · {app.jobSnapshot?.type}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusStyles[app.status]||'bg-slate-100 text-slate-600'}`}>{labels[app.status]||app.status}</span><Link to={`/jobs/${app.jobSlug}`} className="rounded-xl border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-600">View role</Link>{!['rejected','withdrawn','hired'].includes(app.status)&&<button type="button" onClick={()=>setWithdrawTarget(app)} className="rounded-xl border border-red-200 px-3.5 py-2 text-xs font-semibold text-red-700">Withdraw</button>}</div></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Progress</p><div className="mt-3 flex flex-wrap gap-2">{(app.statusHistory||[]).map((entry,index)=><span key={`${entry.status}-${index}`} className="inline-flex items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-[11px] text-slate-600"><Clock3 size={12}/>{labels[entry.status]||entry.status} · {new Date(entry.changedAt).toLocaleDateString()}</span>)}</div></div></article>)}</div>:<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><FileCheck2 size={28} className="mx-auto text-slate-300"/><h3 className="mt-3 font-semibold text-slate-950">No applications in this view</h3><p className="mt-1 text-sm text-slate-500">Try another status or apply to a role.</p></div>}
    <ActionModal open={resumeModal} title="Add your resume before applying" description="A current resume is mandatory for every RB Service Connect application so recruiters receive a complete candidate submission." confirmLabel="Go to Resume" cancelLabel="Not now" onClose={()=>setResumeModal(false)} onConfirm={()=>navigate('/candidate/resume')}/>
    <ActionModal open={Boolean(withdrawTarget)} title="Withdraw this application?" description={withdrawTarget?`Your application for “${withdrawTarget.jobSnapshot?.title||'this role'}” will be marked withdrawn. This action cannot be reversed from the candidate workspace.`:''} confirmLabel="Withdraw application" tone="danger" busy={withdrawing} onClose={()=>!withdrawing&&setWithdrawTarget(null)} onConfirm={withdraw}/>
  </section>;
}
function State({text}){return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500"><BriefcaseBusiness size={22} className="mx-auto mb-2 text-slate-300"/>{text}</div>}
