import { Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api.js';

const blankExperience={title:'',company:'',location:'',startDate:'',endDate:'',current:false,description:''};
const blankEducation={institution:'',degree:'',field:'',startYear:'',endYear:''};
const inputClass='w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-normal text-slate-950 outline-none transition focus:border-amber-400 focus:ring-4 focus:ring-amber-100 disabled:bg-slate-100 disabled:text-slate-400';
const smallButtonClass='inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 transition hover:border-amber-300 hover:bg-amber-50';

export default function CandidateProfilePage(){
  const [profile,setProfile]=useState(null);const [completion,setCompletion]=useState(0);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  useEffect(()=>{let cancelled=false;apiRequest('/candidate/profile').then((r)=>{if(!cancelled){setProfile(r.profile);setCompletion(r.completion);}}).catch((e)=>!cancelled&&setMessage(e.message));return()=>{cancelled=true;};},[]);
  if(!profile)return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">{message||'Loading profile…'}</div>;
  const set=(field,value)=>setProfile((p)=>({...p,[field]:value}));
  const setPref=(field,value)=>setProfile((p)=>({...p,preferences:{...p.preferences,[field]:value}}));
  const updateList=(list,index,field,value)=>setProfile((p)=>({...p,[list]:p[list].map((item,i)=>i===index?{...item,[field]:value}:item)}));
  const remove=(list,index)=>setProfile((p)=>({...p,[list]:p[list].filter((_,i)=>i!==index)}));
  const save=async(e)=>{e.preventDefault();setSaving(true);setMessage('');try{const r=await apiRequest('/candidate/profile',{method:'PUT',body:JSON.stringify(profile)});setProfile(r.profile);setCompletion(r.completion);setMessage('Profile saved successfully.');}catch(err){setMessage(err.message);}finally{setSaving(false);}};
  return <form onSubmit={save} className="space-y-6">
    <Header completion={completion}/>
    {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
    <Section title="Professional profile" subtitle="The core information recruiters will use to understand your background.">
      <div className="grid gap-4 md:grid-cols-2">
        <Field label="Headline"><input value={profile.headline||''} onChange={(e)=>set('headline',e.target.value)} className={inputClass} placeholder="Frontend Developer · React · Accessibility"/></Field>
        <Field label="Phone"><input value={profile.phone||''} onChange={(e)=>set('phone',e.target.value)} className={inputClass} placeholder="Your contact number"/></Field>
        <Field label="Location"><input value={profile.location||''} onChange={(e)=>set('location',e.target.value)} className={inputClass} placeholder="City, State"/></Field>
        <Field label="Skills (comma separated)"><input value={(profile.skills||[]).join(', ')} onChange={(e)=>set('skills',toList(e.target.value))} className={inputClass} placeholder="React, JavaScript, Tailwind CSS"/></Field>
        <Field label="Portfolio URL"><input value={profile.portfolioUrl||''} onChange={(e)=>set('portfolioUrl',e.target.value)} className={inputClass} placeholder="https://..."/></Field>
        <Field label="LinkedIn URL"><input value={profile.linkedinUrl||''} onChange={(e)=>set('linkedinUrl',e.target.value)} className={inputClass} placeholder="https://linkedin.com/in/..."/></Field>
      </div>
      <Field label="Professional summary" className="mt-4"><textarea value={profile.bio||''} onChange={(e)=>set('bio',e.target.value)} rows="5" className={`${inputClass} resize-none`} placeholder="Summarize your experience, strengths, and what you want to do next."/></Field>
    </Section>

    <Section title="Experience" subtitle="Add the roles that best explain your professional history." action={<button type="button" onClick={()=>setProfile(p=>({...p,experience:[...(p.experience||[]),{...blankExperience}]}))} className={smallButtonClass}><Plus size={15}/> Add role</button>}>
      <div className="space-y-4">{(profile.experience||[]).map((item,index)=><div key={item._id||index} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex justify-end"><button type="button" onClick={()=>remove('experience',index)} className="text-slate-400 transition hover:text-red-600" aria-label="Remove experience"><Trash2 size={17}/></button></div><div className="grid gap-4 md:grid-cols-2"><Field label="Job title"><input value={item.title||''} onChange={(e)=>updateList('experience',index,'title',e.target.value)} className={inputClass}/></Field><Field label="Company"><input value={item.company||''} onChange={(e)=>updateList('experience',index,'company',e.target.value)} className={inputClass}/></Field><Field label="Location"><input value={item.location||''} onChange={(e)=>updateList('experience',index,'location',e.target.value)} className={inputClass}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Start"><input value={item.startDate||''} onChange={(e)=>updateList('experience',index,'startDate',e.target.value)} className={inputClass} placeholder="Jan 2023"/></Field><Field label="End"><input value={item.endDate||''} disabled={item.current} onChange={(e)=>updateList('experience',index,'endDate',e.target.value)} className={inputClass} placeholder="Present"/></Field></div></div><label className="mt-3 flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={Boolean(item.current)} onChange={(e)=>updateList('experience',index,'current',e.target.checked)}/> I currently work here</label><Field label="Description" className="mt-4"><textarea value={item.description||''} onChange={(e)=>updateList('experience',index,'description',e.target.value)} rows="3" className={`${inputClass} resize-none`}/></Field></div>)}{!profile.experience?.length&&<Empty text="No experience added yet."/>}</div>
    </Section>

    <Section title="Education" subtitle="Add qualifications that support your applications." action={<button type="button" onClick={()=>setProfile(p=>({...p,education:[...(p.education||[]),{...blankEducation}]}))} className={smallButtonClass}><Plus size={15}/> Add education</button>}>
      <div className="space-y-4">{(profile.education||[]).map((item,index)=><div key={item._id||index} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex justify-end"><button type="button" onClick={()=>remove('education',index)} className="text-slate-400 transition hover:text-red-600" aria-label="Remove education"><Trash2 size={17}/></button></div><div className="grid gap-4 md:grid-cols-2"><Field label="Institution"><input value={item.institution||''} onChange={(e)=>updateList('education',index,'institution',e.target.value)} className={inputClass}/></Field><Field label="Degree"><input value={item.degree||''} onChange={(e)=>updateList('education',index,'degree',e.target.value)} className={inputClass}/></Field><Field label="Field of study"><input value={item.field||''} onChange={(e)=>updateList('education',index,'field',e.target.value)} className={inputClass}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Start year"><input value={item.startYear||''} onChange={(e)=>updateList('education',index,'startYear',e.target.value)} className={inputClass}/></Field><Field label="End year"><input value={item.endYear||''} onChange={(e)=>updateList('education',index,'endYear',e.target.value)} className={inputClass}/></Field></div></div></div>)}{!profile.education?.length&&<Empty text="No education added yet."/>}</div>
    </Section>

    <Section title="Job preferences" subtitle="Help the workspace prioritize roles that better match what you want next."><div className="grid gap-4 md:grid-cols-2"><Field label="Job types"><input value={(profile.preferences?.jobTypes||[]).join(', ')} onChange={(e)=>setPref('jobTypes',toList(e.target.value))} className={inputClass} placeholder="Full-time, Contract"/></Field><Field label="Work modes"><input value={(profile.preferences?.workplaces||[]).join(', ')} onChange={(e)=>setPref('workplaces',toList(e.target.value))} className={inputClass} placeholder="Remote, Hybrid"/></Field><Field label="Preferred locations"><input value={(profile.preferences?.preferredLocations||[]).join(', ')} onChange={(e)=>setPref('preferredLocations',toList(e.target.value))} className={inputClass} placeholder="Jodhpur, Jaipur, Remote"/></Field><Field label="Minimum salary"><input value={profile.preferences?.minimumSalary||''} onChange={(e)=>setPref('minimumSalary',e.target.value)} className={inputClass} placeholder="₹6L"/></Field></div><label className="mt-4 flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={profile.preferences?.openToWork!==false} onChange={(e)=>setPref('openToWork',e.target.checked)}/> Open to work</label></Section>
    <div className="sticky bottom-4 z-20 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white shadow-xl shadow-amber-900/15 disabled:opacity-60"><Save size={16}/>{saving?'Saving…':'Save profile'}</button></div>
  </form>;
}
function Header({completion}){return <div className="rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#F3E8A2]">Candidate profile</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-semibold tracking-[-.04em]">Make your experience easy to understand.</h2><p className="mt-2 text-sm text-slate-400">Keep your background, skills, and preferences current.</p></div><div className="min-w-44"><div className="flex justify-between text-xs"><span className="text-slate-400">Completion</span><strong>{completion}%</strong></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#E3A341]" style={{width:`${completion}%`}}/></div></div></div></div>}
function Section({title,subtitle,action,children}){return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-semibold text-slate-950">{title}</h3><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action}</div>{children}</section>}
function Field({label,className='',children}){return <label className={`block text-sm font-semibold text-slate-700 ${className}`}><span className="mb-2 block">{label}</span>{children}</label>}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-400">{text}</div>}
function toList(value){return value.split(',').map((item)=>item.trim()).filter(Boolean);}
