import { BriefcaseBusiness, ChevronDown, Clock3, FileCheck2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiRequest } from '../../lib/api.js';

const labels={applied:'Applied',reviewing:'Under review',shortlisted:'Shortlisted',interview:'Interview',offered:'Offer',hired:'Hired',rejected:'Rejected',withdrawn:'Withdrawn'};
const statusStyles={applied:'bg-slate-100 text-slate-700',reviewing:'bg-blue-50 text-blue-700',shortlisted:'bg-[#F3E8A2]/70 text-amber-800',interview:'bg-violet-50 text-violet-700',offered:'bg-emerald-50 text-emerald-700',hired:'bg-emerald-100 text-emerald-800',rejected:'bg-red-50 text-red-700',withdrawn:'bg-slate-100 text-slate-500'};

export default function CandidateApplicationsPage(){
  const [searchParams]=useSearchParams();const requestedJob=searchParams.get('job')||'';
  const [applications,setApplications]=useState(null);const [jobs,setJobs]=useState([]);const [filter,setFilter]=useState('all');const [form,setForm]=useState({jobSlug:requestedJob,coverLetter:''});const [message,setMessage]=useState('');const [submitting,setSubmitting]=useState(false);const [showApply,setShowApply]=useState(Boolean(requestedJob));
  useEffect(()=>{let cancelled=false;Promise.all([apiRequest('/candidate/applications'),apiRequest('/public/jobs')]).then(([apps,jobsResponse])=>{if(!cancelled){setApplications(apps.applications||[]);setJobs(jobsResponse.jobs||[]);}}).catch((e)=>!cancelled&&setMessage(e.message));return()=>{cancelled=true;};},[]);
  const visible=useMemo(()=>!applications?[]:filter==='all'?applications:applications.filter((item)=>item.status===filter),[applications,filter]);
  const apply=async(e)=>{e.preventDefault();if(!form.jobSlug){setMessage('Choose a job first.');return;}setSubmitting(true);setMessage('');try{const r=await apiRequest('/candidate/applications',{method:'POST',body:JSON.stringify(form)});setApplications((current)=>[r.application,...(current||[])]);setForm({jobSlug:'',coverLetter:''});setShowApply(false);setMessage(r.message);}catch(err){setMessage(err.message);}finally{setSubmitting(false);}};
  const withdraw=async(id)=>{try{const r=await apiRequest(`/candidate/applications/${id}/withdraw`,{method:'PATCH'});setApplications((current)=>current.map((item)=>item._id===id?r.application:item));setMessage(r.message);}catch(err){setMessage(err.message);}};
  if(!applications)return <State text={message||'Loading applications…'}/>;
  return <section className="space-y-6">
    <div className="rounded-[2rem] bg-[#879E83] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/80">Applications</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-slate-950 sm:text-4xl">Know where every application stands.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-900/70">Submit applications, review status history, and withdraw active applications when your plans change.</p></div><button type="button" onClick={()=>setShowApply((v)=>!v)} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{showApply?'Close form':'Apply to a role'}</button></div></div>
    {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
    {showApply&&<form onSubmit={apply} className="rounded-[1.7rem] border border-amber-200 bg-[#F3E8A2]/35 p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><label className="text-sm font-semibold text-slate-700"><span className="mb-2 block">Choose job</span><div className="relative"><select value={form.jobSlug} onChange={(e)=>setForm({...form,jobSlug:e.target.value})} className="w-full appearance-none rounded-xl border border-slate-200 bg-white px-4 py-3 pr-10 text-sm outline-none"><option value="">Select an opportunity</option>{jobs.map((job)=><option key={job.slug} value={job.slug}>{job.title} — {job.company}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"/></div></label><label className="text-sm font-semibold text-slate-700"><span className="mb-2 block">Cover note (optional)</span><textarea value={form.coverLetter} onChange={(e)=>setForm({...form,coverLetter:e.target.value})} rows="4" className="w-full resize-none rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none" placeholder="Why are you interested in this role?"/></label></div><div className="mt-4 flex justify-end"><button disabled={submitting} className="rounded-xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{submitting?'Submitting…':'Submit application'}</button></div></form>}
    <div className="flex flex-wrap gap-2">{['all','applied','reviewing','shortlisted','interview','offered','hired','rejected','withdrawn'].map((item)=><button key={item} type="button" onClick={()=>setFilter(item)} className={`rounded-xl px-3.5 py-2 text-xs font-semibold capitalize ${filter===item?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{item==='reviewing'?'Under review':item}</button>)}</div>
    {visible.length?<div className="space-y-4">{visible.map((app)=><article key={app._id} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="flex min-w-0 items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-slate-950 text-sm font-bold text-white">{app.jobSnapshot?.initials||'RB'}</span><div className="min-w-0"><p className="text-xs font-medium text-slate-500">{app.jobSnapshot?.company}</p><h3 className="mt-1 text-lg font-semibold text-slate-950">{app.jobSnapshot?.title}</h3><p className="mt-2 text-xs text-slate-500">{app.jobSnapshot?.location} · {app.jobSnapshot?.workplace} · {app.jobSnapshot?.type}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusStyles[app.status]||'bg-slate-100 text-slate-600'}`}>{labels[app.status]||app.status}</span><Link to={`/jobs/${app.jobSlug}`} className="rounded-xl border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-600">View role</Link>{!['rejected','withdrawn','hired'].includes(app.status)&&<button type="button" onClick={()=>withdraw(app._id)} className="rounded-xl border border-red-200 px-3.5 py-2 text-xs font-semibold text-red-700">Withdraw</button>}</div></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Progress</p><div className="mt-3 flex flex-wrap gap-2">{(app.statusHistory||[]).map((entry,index)=><span key={`${entry.status}-${index}`} className="inline-flex items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-[11px] text-slate-600"><Clock3 size={12}/>{labels[entry.status]||entry.status} · {new Date(entry.changedAt).toLocaleDateString()}</span>)}</div></div></article>)}</div>:<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><FileCheck2 size={28} className="mx-auto text-slate-300"/><h3 className="mt-3 font-semibold text-slate-950">No applications in this view</h3><p className="mt-1 text-sm text-slate-500">Try another status or apply to a role.</p></div>}
  </section>;
}
function State({text}){return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500"><BriefcaseBusiness size={22} className="mx-auto mb-2 text-slate-300"/>{text}</div>}
