import { FileText, Link2, Trash2, UploadCloud } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api.js';

export default function CandidateResumePage(){
  const [resume,setResume]=useState({name:'',url:'',updatedAt:null});const [form,setForm]=useState({name:'',url:''});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  useEffect(()=>{let cancelled=false;apiRequest('/candidate/profile').then((r)=>{if(!cancelled){const next=r.profile?.resume||{name:'',url:'',updatedAt:null};setResume(next);setForm({name:next.name||'',url:next.url||''});}}).catch((e)=>!cancelled&&setMessage(e.message));return()=>{cancelled=true;};},[]);
  const save=async(e)=>{e.preventDefault();setSaving(true);setMessage('');try{const r=await apiRequest('/candidate/resume',{method:'PUT',body:JSON.stringify(form)});setResume(r.resume);setMessage(r.message);}catch(err){setMessage(err.message);}finally{setSaving(false);}};
  const remove=async()=>{setSaving(true);setMessage('');try{const r=await apiRequest('/candidate/resume',{method:'DELETE'});setResume({name:'',url:'',updatedAt:null});setForm({name:'',url:''});setMessage(r.message);}catch(err){setMessage(err.message);}finally{setSaving(false);}};
  return <section className="space-y-6">
    <div className="rounded-[2rem] bg-[#879E83] p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-white/25 text-slate-950"><UploadCloud size={22}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/80">Resume</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Keep one current resume ready.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-900/70">Add a secure public or cloud-hosted resume URL. When Cloudinary storage is connected later, this page can switch to direct file upload without changing the application model.</p></div></div></div>
    {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <form onSubmit={save} className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-xl font-semibold text-slate-950">Resume details</h3><p className="mt-1 text-sm text-slate-500">Use a PDF link from a storage provider you control.</p><label className="mt-6 block text-sm font-semibold text-slate-700"><span className="mb-2 block">Display name</span><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none transition focus:border-amber-400 focus:ring-4 focus:ring-amber-100" placeholder="Shahzad-Khan-Resume.pdf"/></label><label className="mt-5 block text-sm font-semibold text-slate-700"><span className="mb-2 block">Resume URL</span><div className="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3 focus-within:border-amber-400 focus-within:ring-4 focus-within:ring-amber-100"><Link2 size={17} className="text-slate-400"/><input value={form.url} onChange={(e)=>setForm({...form,url:e.target.value})} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="https://.../resume.pdf"/></div></label><button disabled={saving} className="mt-6 rounded-xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving?'Saving…':'Save resume'}</button></form>
      <article className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-700">Current resume</p>{resume?.url?<><div className="mt-5 flex items-center gap-4 rounded-2xl bg-slate-50 p-4"><span className="grid size-12 place-items-center rounded-xl bg-[#F3E8A2]/70 text-indigo-700"><FileText size={21}/></span><div className="min-w-0"><strong className="block truncate text-sm text-slate-950">{resume.name}</strong><span className="text-xs text-slate-500">Updated {resume.updatedAt?new Date(resume.updatedAt).toLocaleDateString():'recently'}</span></div></div><div className="mt-5 flex flex-wrap gap-3"><a href={resume.url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Open resume</a><button type="button" onClick={remove} disabled={saving} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700"><Trash2 size={15}/> Remove</button></div></>:<div className="mt-5 rounded-2xl border border-dashed border-slate-300 p-7 text-center text-sm text-slate-400">No resume has been added yet.</div>}</article>
    </div>
  </section>;
}
