import { BookmarkX, BriefcaseBusiness, MapPin } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../lib/api.js';

export default function CandidateSavedJobsPage(){
  const [jobs,setJobs]=useState(null);const [message,setMessage]=useState('');
  const load=()=>apiRequest('/candidate/saved-jobs').then((r)=>setJobs(r.jobs||[])).catch((e)=>setMessage(e.message));
  useEffect(()=>{load();},[]);
  const remove=async(slug)=>{try{await apiRequest(`/candidate/saved-jobs/${slug}`,{method:'DELETE'});setJobs((current)=>current.filter((job)=>job.slug!==slug));}catch(e){setMessage(e.message);}};
  if(!jobs)return <State text={message||'Loading saved jobs…'}/>;
  return <section className="space-y-6"><div className="rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#F3E8A2]">Saved opportunities</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Keep promising roles close.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Save jobs while researching, compare them later, and remove anything that no longer fits.</p></div>{message&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{message}</div>}{jobs.length?<div className="grid gap-4 xl:grid-cols-2">{jobs.map((job)=><article key={job.slug} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:border-amber-300 hover:shadow-lg"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-[#879E83] text-sm font-bold text-white">{job.initials}</span><div className="min-w-0 flex-1"><p className="text-xs font-medium text-slate-500">{job.company}</p><h3 className="mt-1 text-lg font-semibold text-slate-950">{job.title}</h3><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><MapPin size={14}/>{job.location} · {job.workplace}</span><span className="inline-flex items-center gap-1.5"><BriefcaseBusiness size={14}/>{job.experience} · {job.type}</span></div></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><strong className="text-sm text-slate-700">{job.salary}</strong><div className="flex gap-2"><button type="button" onClick={()=>remove(job.slug)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-600 hover:border-red-200 hover:text-red-700"><BookmarkX size={15}/> Remove</button><Link to={`/jobs/${job.slug}`} className="rounded-xl bg-[#E3A341] px-4 py-2 text-xs font-semibold text-white">View role</Link></div></div></article>)}</div>:<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><BookmarkX size={28} className="mx-auto text-slate-300"/><h3 className="mt-3 font-semibold text-slate-950">No saved jobs yet</h3><p className="mt-1 text-sm text-slate-500">Browse opportunities and save roles you want to revisit.</p><Link to="/jobs" className="mt-5 inline-block rounded-xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white">Browse jobs</Link></div>}</section>;
}
function State({text}){return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">{text}</div>}
