import Notification from '../models/Notification.js';
import SuccessFee from '../models/SuccessFee.js';
import User from '../models/User.js';
import { brandedEmail,sendEmail } from './emailService.js';

const DAY=86400000;const startOfDay=(value)=>{const date=new Date(value);date.setHours(0,0,0,0);return date;};const dateKey=(value)=>startOfDay(value).toISOString().slice(0,10);const money=(value)=>`₹${Math.round(Number(value)||0).toLocaleString('en-IN')}`;
async function alreadySent(user,feeId,installmentNumber,kind,key){return Notification.exists({user,type:'payment_reminder','metadata.successFeeId':feeId,'metadata.installmentNumber':installmentNumber,'metadata.kind':kind,'metadata.key':key});}
export async function runBillingReminders(now=new Date()){const today=startOfDay(now);const fees=await SuccessFee.find({'billing.activatedAt':{$ne:null},status:{$in:['payment_due','partially_paid']}}).populate('job','title').lean();if(!fees.length)return{checked:0,sent:0};const users=await User.find({_id:{$in:[...new Set(fees.map((fee)=>String(fee.candidate)))]},status:'active'}).select('firstName email').lean();const userMap=new Map(users.map((user)=>[String(user._id),user]));let sent=0;for(const fee of fees){const user=userMap.get(String(fee.candidate));if(!user)continue;for(const installment of fee.billing?.installments||[]){if(['paid','waived'].includes(installment.status))continue;const due=startOfDay(installment.dueAt);const days=Math.round((due-today)/DAY);let kind='';if(days===7)kind='due_7_days';else if(days===3)kind='due_3_days';else if(days===1)kind='due_tomorrow';else if(days===0)kind='due_today';else if(days<0&&Math.abs(days)%7===0)kind='overdue_weekly';if(!kind)continue;const key=dateKey(today);if(await alreadySent(user._id,fee._id,installment.number,kind,key))continue;const overdue=days<0;const title=overdue?'Career Programme payment overdue':days===0?'Career Programme payment due today':'Career Programme payment reminder';const timing=overdue?`${Math.abs(days)} day${Math.abs(days)===1?'':'s'} overdue`:days===0?'due today':`due in ${days} day${days===1?'':'s'}`;const message=`Instalment ${installment.number} of ${money(installment.amount)} for ${fee.job?.title||'your verified placement'} is ${timing}.`;await Notification.create({user:user._id,type:'payment_reminder',title,message,link:'/candidate/billing',metadata:{successFeeId:fee._id,installmentNumber:installment.number,kind,key}});await sendEmail({to:user.email,subject:title,html:brandedEmail({eyebrow:'Payment reminder',title,greeting:`Hello ${user.firstName},`,paragraphs:[message,'Open Billing & Payments to review your verified programme fee schedule and payment history.'],buttonLabel:'Review billing',buttonUrl:`${process.env.CLIENT_URL}/candidate/billing`,note:'If you have already paid, please allow time for the payment to be reconciled or contact support with your transaction reference.'}),text:`${message} Review billing: ${process.env.CLIENT_URL}/candidate/billing`});sent+=1;}}
return{checked:fees.length,sent};}
export function startBillingReminderWorker(){if(process.env.NODE_ENV==='test')return()=>{};let running=false;const execute=async()=>{if(running)return;running=true;try{await runBillingReminders();}catch(error){console.error('Billing reminder worker failed:',error);}finally{running=false;}};const timer=setInterval(execute,6*60*60*1000);timer.unref?.();setTimeout(execute,15000).unref?.();return()=>clearInterval(timer);}
