import CareerEnrollment from '../models/CareerEnrollment.js';
import Company from '../models/Company.js';
import SuccessFee from '../models/SuccessFee.js';
import { paymentPlans } from '../config/careerPrograms.js';

const addMonths=(date,months)=>{const next=new Date(date);next.setMonth(next.getMonth()+months);return next;};
export function activateBillingSchedule(fee,activationDate=new Date()){if(fee.billing?.activatedAt)return fee;const plan=paymentPlans[fee.paymentPreference]||paymentPlans.full;const count=plan.installments;const total=Math.round(fee.feeAmount);const base=Math.floor(total/count);let allocated=0;const installments=Array.from({length:count},(_,index)=>{const amount=index===count-1?total-allocated:base;allocated+=amount;return{number:index+1,amount,dueAt:index===0?new Date(activationDate):addMonths(activationDate,index),status:index===0?'due':'scheduled',paidAt:null,providerPaymentId:''};});fee.billing={activatedAt:new Date(activationDate),totalAmount:total,paidAmount:0,outstandingAmount:total,nextDueAt:installments[0]?.dueAt||null,installments};fee.status='payment_due';return fee;}
export async function ensureSuccessFeeForHire({application,job,recruiterId}){if(!application?._id||!job?._id||!recruiterId)throw new Error('A valid application, job and recruiter are required to create a success fee.');if(application.status!=='hired')throw new Error('A success fee can only be created for a hired application.');if(String(application.job?._id||application.job)!==String(job._id))throw new Error('Application and job do not match.');if(String(job.createdBy?._id||job.createdBy)!==String(recruiterId))throw new Error('Only the recruiter who owns the job can create its success fee.');let fee=await SuccessFee.findOne({application:application._id});if(fee)return fee;const candidateId=application.candidate?._id||application.candidate;if(!candidateId)throw new Error('The hired application does not have a valid candidate.');const enrollment=await CareerEnrollment.findOne({candidate:candidateId,status:'active'}).sort({createdAt:-1});if(!enrollment)return null;const company=await Company.findById(job.company).select('_id').lean();if(!company)return null;const plan=paymentPlans[enrollment.paymentPreference]||paymentPlans.full;const payableTotal=Math.round(enrollment.successFeeAmount*plan.multiplier);if(!Number.isFinite(payableTotal)||payableTotal<0)throw new Error('The success fee amount is invalid.');try{fee=await SuccessFee.create({application:application._id,job:job._id,candidate:candidateId,recruiter:recruiterId,company:company._id,careerEnrollment:enrollment._id,status:'awaiting_candidate_confirmation',feePercent:0,firstSalaryAmount:0,feeAmount:payableTotal,currency:'INR',paymentPreference:enrollment.paymentPreference});}catch(error){if(error?.code===11000){fee=await SuccessFee.findOne({application:application._id});if(fee)return fee;}throw error;}const placementResult=await CareerEnrollment.updateOne({_id:enrollment._id,status:'active'},{$set:{status:'placed',placedApplication:application._id,placedAt:new Date()}});if(!placementResult.modifiedCount){await SuccessFee.deleteOne({_id:fee._id,status:'awaiting_candidate_confirmation','recruiterConfirmation.confirmed':false,'candidateConfirmation.confirmed':false});return null;}return fee;}
export function reconcileHireConfirmations(fee){const recruiterSalary=Number(fee.recruiterConfirmation.salaryAmount)||0,candidateSalary=Number(fee.candidateConfirmation.salaryAmount)||0;if(!fee.recruiterConfirmation.confirmed||!fee.candidateConfirmation.confirmed)return fee;if(!recruiterSalary||!candidateSalary)return fee;const difference=Math.abs(recruiterSalary-candidateSalary);const tolerance=Math.max(1000,Math.round(Math.max(recruiterSalary,candidateSalary)*0.02));if(difference>tolerance){fee.status='disputed';fee.dispute.reason='Recruiter and candidate salary confirmations do not match.';fee.dispute.openedAt=new Date();return fee;}fee.firstSalaryAmount=Math.round((recruiterSalary+candidateSalary)/2);fee.status='awaiting_first_salary';return fee;}
