import fs from 'node:fs';import path from 'node:path';
const root=path.resolve('client/src');const violations=[];
const globalPatterns=[{name:'native <select>',regex:/<select\b/g},{name:'native checkbox/radio/date/time control',regex:/type\s*=\s*["'](?:checkbox|radio|date|datetime-local|time|month|week|color)["']/g},{name:'browser alert/confirm/prompt',regex:/\b(?:window\.)?(?:alert|confirm|prompt)\s*\(/g}];
const sharedUiRoot=path.resolve(root,'components/ui');
function lineAt(text,index){return text.slice(0,index).split('\n').length;}
function record(text,file,patterns){for(const pattern of patterns){for(const match of text.matchAll(pattern.regex))violations.push(`${path.relative(process.cwd(),file)}:${lineAt(text,match.index)} ${pattern.name}`);}}
function openingTag(text,start){let quote='';let braces=0;for(let i=start;i<text.length;i+=1){const char=text[i];const prev=text[i-1];if(quote){if(char===quote&&prev!=='\\')quote='';continue;}if(char==='"'||char==="'"||char==='`'){quote=char;continue;}if(char==='{'){braces+=1;continue;}if(char==='}'&&braces>0){braces-=1;continue;}if(char==='>'&&braces===0)return text.slice(start,i+1);}return text.slice(start);}
function nativeElements(text,tag){const results=[];let cursor=0;const startToken=`<${tag}`;while(cursor<text.length){const start=text.indexOf(startToken,cursor);if(start<0)break;const boundary=text[start+startToken.length];if(boundary&&/[A-Za-z0-9_-]/.test(boundary)){cursor=start+startToken.length;continue;}const markup=openingTag(text,start);results.push({index:start,markup});cursor=start+Math.max(markup.length,startToken.length);}return results;}
function recordUnstyledControls(text,file){if(file.startsWith(`${sharedUiRoot}${path.sep}`))return;for(const tag of ['input','textarea']){for(const match of nativeElements(text,tag)){const markup=match.markup;const isHiddenFile=tag==='input'&&/type\s*=\s*["']file["']/.test(markup)&&/\bsr-only\b/.test(markup);const isStyled=/className\s*=/.test(markup);if(!isStyled&&!isHiddenFile)violations.push(`${path.relative(process.cwd(),file)}:${lineAt(text,match.index)} unstyled native <${tag}> control`);}}
}
function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())walk(file);else if(/\.(?:jsx|js)$/.test(entry.name)){const text=fs.readFileSync(file,'utf8');record(text,file,globalPatterns);recordUnstyledControls(text,file);}}}
walk(root);if(violations.length){console.error('Custom UI audit failed:\n'+violations.map((item)=>`- ${item}`).join('\n'));process.exit(1);}console.log('Custom UI audit passed. Native browser-default controls and dialogs are not allowed; text controls must use the shared primitives or explicit custom styling.');
