import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const appFile = path.join(root, 'server', 'src', 'app.js');
const routesRoot = path.join(root, 'server', 'src', 'routes');
const clientRoot = path.join(root, 'client', 'src');

const failures = [];
const warnings = [];

function read(file) { return fs.readFileSync(file, 'utf8'); }
function walk(dir, predicate) { const files=[]; for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const target=path.join(dir,entry.name);if(entry.isDirectory())files.push(...walk(target,predicate));else if(!predicate||predicate(target))files.push(target);} return files; }
function joinRoute(base,route){const cleanBase=String(base||'').replace(/\/$/,'');const cleanRoute=String(route||'').replace(/^\//,'');const joined=`${cleanBase}/${cleanRoute}`.replace(/\/{2,}/g,'/');return joined.length>1?joined.replace(/\/$/,''):joined;}
function clientPath(serverPath){return serverPath.startsWith('/api')?serverPath.slice(4)||'/':serverPath;}
function normalizePath(value){let result=String(value||'').trim();result=result.replace(/\$\{([^}]+)\}/g,(_match,expression)=>{const name=String(expression||'').trim();return /(?:base|endpoint|path)$/i.test(name)?':dynamic*':':dynamic';});result=result.split('?')[0].split('#')[0];result=result.replace(/\/{2,}/g,'/');if(!result.startsWith('/'))result=`/${result}`;if(result.length>1)result=result.replace(/\/$/,'');return result;}
function matchesRoute(candidate,route){const left=normalizePath(candidate).split('/').filter(Boolean);const right=normalizePath(route).split('/').filter(Boolean);function matchFrom(li,ri){if(li===left.length&&ri===right.length)return true;if(li===left.length||ri===right.length)return false;const segment=left[li],other=right[ri];if(segment===':dynamic*'){for(let next=ri+1;next<=right.length;next+=1)if(matchFrom(li+1,next))return true;return false;}if(segment===other||segment.startsWith(':')||other.startsWith(':'))return matchFrom(li+1,ri+1);return false;}return matchFrom(0,0);}
function lineAt(text,index){return text.slice(0,index).split('\n').length;}
function parseServerRoutes(){const app=read(appFile);const routeImports=new Map();for(const match of app.matchAll(/import\s+([A-Za-z_$][\w$]*)\s+from\s+['"]\.\/routes\/([^'"]+)['"]/g))routeImports.set(match[1],match[2]);const mounts=new Map();for(const match of app.matchAll(/app\.use\(\s*['"]([^'"]+)['"]\s*,\s*([A-Za-z_$][\w$]*)\s*\)/g)){const[,mount,variable]=match;if(routeImports.has(variable))mounts.set(routeImports.get(variable),mount);}const routeFiles=walk(routesRoot,file=>file.endsWith('Routes.js'));for(const file of routeFiles){const name=path.basename(file);if(!mounts.has(name))failures.push(`Server route file is not mounted in app.js: server/src/routes/${name}`);}const endpoints=[];for(const[fileName,mount]of mounts.entries()){const file=path.join(routesRoot,fileName);if(!fs.existsSync(file)){failures.push(`Mounted route file does not exist: server/src/routes/${fileName}`);continue;}const text=read(file);for(const match of text.matchAll(/router\.(get|post|put|patch|delete)\(\s*['"]([^'"]+)['"]/gi))endpoints.push({method:match[1].toUpperCase(),path:clientPath(joinRoute(mount,match[2])),source:`server/src/routes/${fileName}:${lineAt(text,match.index)}`});}for(const match of app.matchAll(/app\.(get|post|put|patch|delete)\(\s*['"](\/api\/[^'"]+)['"]/gi))endpoints.push({method:match[1].toUpperCase(),path:clientPath(match[2]),source:`server/src/app.js:${lineAt(app,match.index)}`});const seen=new Map();for(const endpoint of endpoints){const key=`${endpoint.method} ${normalizePath(endpoint.path)}`;if(seen.has(key))failures.push(`Duplicate API route: ${key} (${seen.get(key)} and ${endpoint.source})`);else seen.set(key,endpoint.source);}return endpoints;}
function readQuoted(text,start){const quote=text[start];let escaped=false;for(let index=start+1;index<text.length;index+=1){const char=text[index];if(escaped){escaped=false;continue;}if(char==='\\'){escaped=true;continue;}if(char===quote)return{raw:text.slice(start+1,index),end:index+1};}return null;}
function callTail(text,start){let parens=1,quote='',escaped=false;for(let index=start;index<text.length;index+=1){const char=text[index];if(quote){if(escaped)escaped=false;else if(char==='\\')escaped=true;else if(char===quote)quote='';continue;}if(char==='\''||char==='"'||char==='`'){quote=char;continue;}if(char==='(')parens+=1;else if(char===')'){parens-=1;if(parens===0)return text.slice(start,index);}}return text.slice(start);}
function escapeRegExp(value){return String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function resolveSimpleIdentifier(text,identifier,beforeIndex){const prefix=text.slice(0,beforeIndex);const declaration=new RegExp('\\b(?:const|let|var)\\s+'+escapeRegExp(identifier)+'\\s*=\\s*([\'"`])','g');let found=null;for(const match of prefix.matchAll(declaration))found=match;if(!found)return null;const quoteIndex=found.index+found[0].length-1;const quoted=readQuoted(text,quoteIndex);if(!quoted||quoted.end>beforeIndex)return null;return quoted.raw;}
function parseClientCalls(){const files=walk(clientRoot,file=>/\.(?:js|jsx)$/.test(file));const calls=[],unresolved=[];for(const file of files){const text=read(file);let cursor=0;while(cursor<text.length){const start=text.indexOf('apiRequest(',cursor);if(start<0)break;let argStart=start+'apiRequest('.length;while(/\s/.test(text[argStart]||''))argStart+=1;let rawPath=null,argumentEnd=argStart;const quote=text[argStart];if(['\'','"','`'].includes(quote)){const quoted=readQuoted(text,argStart);if(!quoted){failures.push(`${path.relative(root,file)}:${lineAt(text,start)} contains an unterminated apiRequest path literal`);break;}rawPath=quoted.raw;argumentEnd=quoted.end;}else{const identifierMatch=text.slice(argStart).match(/^([A-Za-z_$][\w$]*)/);if(identifierMatch){const identifier=identifierMatch[1];rawPath=resolveSimpleIdentifier(text,identifier,start);argumentEnd=argStart+identifier.length;}}if(!rawPath){unresolved.push(`${path.relative(root,file)}:${lineAt(text,start)}`);cursor=Math.max(argStart+1,argumentEnd+1);continue;}let next=argumentEnd;while(/\s/.test(text[next]||''))next+=1;if(text[next]&&![',',')'].includes(text[next])){unresolved.push(`${path.relative(root,file)}:${lineAt(text,start)}`);cursor=argumentEnd+1;continue;}const tail=callTail(text,argumentEnd);const methodMatch=tail.match(/\bmethod\s*:\s*['"](GET|POST|PUT|PATCH|DELETE)['"]/i);calls.push({method:(methodMatch?.[1]||'GET').toUpperCase(),path:normalizePath(rawPath),source:`${path.relative(root,file)}:${lineAt(text,start)}`});cursor=argumentEnd;}}if(unresolved.length)warnings.push(`${unresolved.length} apiRequest call(s) remain too dynamic to match statically: ${unresolved.join(', ')}`);return calls;}

const endpoints=parseServerRoutes();
const clientCalls=parseClientCalls();
for(const call of clientCalls){const connected=endpoints.some(endpoint=>endpoint.method===call.method&&matchesRoute(call.path,endpoint.path));if(!connected)failures.push(`Client API call has no matching server route: ${call.method} ${call.path} (${call.source})`);}
const health=endpoints.some(endpoint=>endpoint.method==='GET'&&normalizePath(endpoint.path)==='/health');if(!health)failures.push('Missing GET /api/health endpoint.');
if(failures.length){console.error(`API wiring audit failed:\n${failures.map(item=>`- ${item}`).join('\n')}`);if(warnings.length)console.error(`Warnings:\n${warnings.map(item=>`- ${item}`).join('\n')}`);process.exit(1);}
console.log(`API wiring audit passed. ${endpoints.length} server routes discovered; ${clientCalls.length} client calls matched.`);if(warnings.length)console.log(`API audit notes:\n${warnings.map(item=>`- ${item}`).join('\n')}`);
