import { ArrowRight,BadgeCheck,BarChart3,BriefcaseBusiness,ClipboardList,CreditCard,MessagesSquare,Megaphone,ShieldCheck,Sparkles,UserRoundSearch,UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
const features=[
{icon:BriefcaseBusiness,title:'Publish structured roles',copy:'Create detailed openings with responsibilities, requirements, compensation, workplace type, skills and application deadlines.'},
{icon:UserRoundSearch,title:'Discover relevant candidates',copy:'Search discoverable candidate profiles and review the professional context needed for stronger screening decisions.'},
{icon:ClipboardList,title:'Manage the complete pipeline',copy:'Move applicants through review, shortlist, interview, offer, hired or rejected stages while keeping decisions organized.'},
{icon:MessagesSquare,title:'Coordinate conversations',copy:'Keep candidate communication, interview scheduling and hiring context connected to the recruitment workflow.'},
{icon:Megaphone,title:'Promote priority opportunities',copy:'Purchase eligible job promotions through verified payment flows and give important openings additional visibility.'},
{icon:BarChart3,title:'Understand hiring activity',copy:'Monitor jobs, applicants and pipeline movement from a recruiter workspace designed around daily hiring operations.'},
];
const proof=[[BadgeCheck,'Verified companies','Company verification protects candidate access and promotion eligibility.'],[ClipboardList,'Structured hiring','Applications progress through clear, auditable recruitment stages.'],[UsersRound,'Candidate discovery','Discoverable profiles help recruiters find talent beyond inbound applications.'],[CreditCard,'Verified payments','Promotion purchases are verified against provider-side payment and order state.']];
const steps=[['01','Create your recruiter account','Register as a recruiter and establish your organization profile.'],['02','Complete company verification','Recruiter capabilities unlock through the platform verification workflow.'],['03','Publish, discover and manage','Create openings, receive applications, discover candidates and coordinate interviews from one workspace.'],['04','Close roles with context','Keep applicant stages, conversations, decisions and hiring activity visible through the final outcome.']];
export default function EmployersPage(){return <>
<section className="relative overflow-hidden bg-[#879E83] text-white"><div className="absolute -right-24 -top-24 size-80 rounded-full bg-[#F3E8A2]/25 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:py-20"><div className="self-center"><div className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3.5 py-2 text-xs font-semibold"><Sparkles size={14}/> Recruitment operations, connected</div><h1 className="mt-6 max-w-3xl text-5xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-[4.4rem] lg:leading-[1.02]">Hire with more clarity and less operational friction.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/85 sm:text-lg">RB Service Connect gives verified recruiters a dedicated workspace for company management, jobs, candidate discovery, applications, interviews, communication, promotions and hiring visibility.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register?role=recruiter" className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3.5 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-indigo-600">Create recruiter account <ArrowRight size={17}/></Link><Link to="/login" className="rounded-xl border border-white/30 bg-white/10 px-5 py-3.5 text-sm font-semibold transition hover:-translate-y-0.5 hover:bg-white/20">Recruiter sign in</Link></div></div><div className="rounded-[2rem] border border-white/20 bg-white p-6 text-slate-950 shadow-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-indigo-700">Recruiter workflow</p><h2 className="mt-2 text-2xl font-semibold">One workspace from opening to hire</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Jobs','Create & manage'],['Candidates','Search & review'],['Applications','Track pipeline'],['Interviews','Schedule & progress'],['Messages','Keep context'],['Promotions','Boost priority roles']].map(([a,b])=><div key={a} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:bg-white hover:shadow-md"><strong className="text-sm">{a}</strong><p className="mt-1 text-xs text-slate-500">{b}</p></div>)}</div><div className="mt-4 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center gap-3"><ShieldCheck size={20} className="text-[#F3E8A2]"/><div><strong className="block text-sm">Verification-aware access</strong><span className="text-xs text-slate-400">Sensitive recruiter capabilities remain tied to company eligibility.</span></div></div></div></div></div></section>
<section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{proof.map(([Icon,title,copy])=><div key={title} className="bg-white px-6 py-7"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#F3E8A2]/65 text-indigo-700"><Icon size={17}/></span><strong className="text-sm text-slate-950">{title}</strong></div><p className="mt-3 text-xs leading-5 text-slate-500">{copy}</p></div>)}</div></section>
<section className="bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-700">Recruitment, organized</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl">Tools that follow the actual hiring workflow.</h2><p className="mt-4 text-base leading-7 text-slate-600">Recruitment capabilities stay connected instead of becoming separate dashboards and spreadsheets.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,copy})=><article key={title} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-amber-300 hover:shadow-xl hover:shadow-black/5"><span className="grid size-11 place-items-center rounded-2xl bg-[#F3E8A2]/70 text-indigo-700"><Icon size={20}/></span><h3 className="mt-5 text-lg font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
<section className="bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[.78fr_1.22fr] lg:px-8"><div className="self-start lg:sticky lg:top-28"><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-700">From account to hire</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950">A hiring flow your team can follow.</h2><p className="mt-4 text-base leading-7 text-slate-600">Clear stages and role-aware controls keep recruiters and candidates aligned on what happens next.</p><Link to="/register?role=recruiter" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-indigo-600">Start hiring <ArrowRight size={16}/></Link></div><div className="space-y-3">{steps.map(([n,t,c])=><article key={n} className="flex gap-4 rounded-3xl border border-slate-200 bg-slate-50 p-5 transition duration-300 hover:-translate-y-0.5 hover:border-emerald-300 hover:bg-white hover:shadow-lg"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#879E83] text-xs font-bold text-white">{n}</span><div><h3 className="text-lg font-semibold text-slate-950">{t}</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">{c}</p></div></article>)}</div></div></section>
<section className="bg-slate-950 py-16 text-white sm:py-20"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-4 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-300">Build your hiring workspace</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Bring your recruitment workflow together.</h2><p className="mt-4 text-base leading-7 text-slate-300">Establish your company, complete verification and manage the journey from role creation through final hiring decisions.</p></div><Link to="/register?role=recruiter" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3.5 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-indigo-400">Create recruiter account <ArrowRight size={16}/></Link></div></section>
</>}
