import { ChevronDown, HelpCircle, MessageCircleQuestion } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';

const faqs = [
  ['Who is RB Service Connect for?', 'RB Service Connect connects candidates, recruiters and platform administrators. Candidates manage profiles, applications, interviews, messages, placements, career programmes and billing, while verified recruiters manage companies, jobs, candidate discovery and hiring pipelines.'],
  ['Can I explore jobs and companies without an account?', 'Yes. Public job listings and company profiles can be explored without signing in. A candidate account is required for authenticated actions such as applying, saving jobs, managing interviews and using your personal workspace.'],
  ['How do recruiter and company verification work?', 'Recruiter access is verification-aware. Company and recruiter eligibility is reviewed before sensitive hiring capabilities are available, helping protect candidate data and keeping employer activity accountable.'],
  ['What can candidates manage from their workspace?', 'Candidates can maintain their professional profile and resume, browse and save jobs, track applications, manage interviews and job alerts, communicate through messages, review placements and career programmes, and access eligible billing, receipts and account settings.'],
  ['What can recruiters manage from their workspace?', 'Recruiters can maintain their company profile, create and manage jobs, review applicants, search discoverable candidates, organize talent pools, schedule interviews, manage placements, communicate with candidates and promote eligible published roles.'],
  ['How does the application pipeline work?', 'Applications use structured stages such as applied, under review, shortlisted, interview, offer, hired, rejected or withdrawn. This keeps candidates and recruiters working from a consistent hiring state instead of disconnected updates.'],
  ['Can recruiters discover candidates who have not applied?', 'Recruiters can search candidate profiles that are eligible and discoverable to recruiters. Candidates retain profile privacy controls, and recruiter access remains subject to platform and company eligibility.'],
  ['How do interviews, messages and notifications fit together?', 'Interview scheduling, conversations and notifications are connected to authenticated workspaces so important hiring activity is easier to follow without relying on unrelated tools or browser prompts.'],
  ['What are Career Programmes and placements?', 'Career Programme workflows allow eligible candidate journeys, placement activity and related billing states to be managed inside the platform. Placement and programme records remain separate from ordinary job applications so each workflow keeps the right context.'],
  ['How are payments and receipts handled?', 'Eligible platform purchases and billing flows use explicit payment states and server-side verification. Where receipts or refunds apply, they are connected to the relevant transaction record rather than relying only on a client-side success message.'],
  ['What is AutoPay?', 'AutoPay currently includes a clearly labelled demo simulation for eligible Career Programme instalment plans. It demonstrates scheduling, ledger and receipt behaviour without creating or storing a real bank, card or UPI mandate.'],
  ['How do promoted jobs and profile boosts work?', 'Eligible recruiters can promote published jobs and eligible candidates can use supported profile-promotion flows. Promotion eligibility is checked against the current account and target state so an ineligible or expired target cannot simply be activated from an older order.'],
  ['How is account access separated?', 'Candidate, recruiter and administrator areas use role-aware authentication and protected routes. Each account type receives navigation and controls intended for that role instead of sharing one unrestricted dashboard.'],
  ['Can I reset a forgotten password or verify my email?', 'Yes. Authentication includes email verification and password recovery flows. Reset links are time-limited, and the sign-in experience keeps candidate and recruiter access within the same secure authentication system.'],
  ['What should I do if I need help or notice a safety issue?', 'Use the Contact page for general, candidate, recruiter, verification or accessibility help. Authenticated candidate and recruiter workspaces also include safety-related areas for issues that belong to an account context. Never send passwords or payment credentials in a support message.'],
];

export default function FaqPage() {
  const [openIndex, setOpenIndex] = useState(0);
  return <>
    <section className="overflow-hidden bg-[#F3E8A2]/60"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 sm:py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="self-center"><span className="inline-flex items-center gap-2 rounded-full border border-amber-300/70 bg-white/70 px-3.5 py-2 text-xs font-bold uppercase tracking-[0.16em] text-indigo-700"><HelpCircle size={14}/> Help centre</span><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-5xl lg:text-6xl">Answers for the complete recruitment journey.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">Understand accounts, verification, jobs, applications, candidate discovery, interviews, career programmes, payments, promotions, security and support.</p></div><div className="rounded-[2rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-amber-900/5 backdrop-blur sm:p-8"><MessageCircleQuestion size={26} className="text-indigo-700"/><h2 className="mt-4 text-2xl font-semibold tracking-[-0.03em] text-slate-950">Need help with your account or workflow?</h2><p className="mt-3 text-sm leading-7 text-slate-600">Send your question through the relevant support topic so candidate, recruiter, verification and general enquiries keep the right context.</p><Link to="/contact" className="mt-6 inline-flex rounded-xl bg-indigo-500 px-4 py-3 text-sm font-semibold text-white transition duration-200 hover:-translate-y-0.5 hover:bg-indigo-600 hover:shadow-lg">Contact support</Link></div></div></section>
    <section className="bg-white py-14 sm:py-18"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><div className="space-y-3">{faqs.map(([question,answer],index)=>{const isOpen=openIndex===index;return <article key={question} className={`overflow-hidden rounded-2xl border transition duration-200 ${isOpen?'border-indigo-300 bg-[#F3E8A2]/20 shadow-md shadow-black/5':'border-slate-200 bg-slate-50 hover:-translate-y-0.5 hover:border-emerald-300 hover:bg-white hover:shadow-md'}`}><button type="button" className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left sm:px-6" aria-expanded={isOpen} onClick={()=>setOpenIndex(current=>current===index?-1:index)}><span className="font-semibold text-slate-950">{question}</span><span className={`grid size-9 shrink-0 place-items-center rounded-full transition ${isOpen?'bg-indigo-500 text-white':'bg-white text-slate-500'}`}><ChevronDown size={18} className={`transition-transform duration-200 ${isOpen?'rotate-180':''}`}/></span></button><div className={`grid transition-[grid-template-rows] duration-200 ${isOpen?'grid-rows-[1fr]':'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className="px-5 pb-5 pr-14 text-sm leading-7 text-slate-600 sm:px-6 sm:pb-6 sm:pr-16">{answer}</p></div></div></article>})}</div></div></section>
  </>;
}
