import { Check,ChevronDown } from 'lucide-react';
import { useEffect,useId,useRef,useState } from 'react';

export default function CustomSelect({label,value,onChange,options=[],placeholder='Select an option',disabled=false,className=''}){
  const [open,setOpen]=useState(false);const rootRef=useRef(null);const listId=useId();const selected=options.find((option)=>(option.value??option)===value);
  useEffect(()=>{const close=(event)=>{if(rootRef.current&&!rootRef.current.contains(event.target))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
  const choose=(option)=>{if(disabled)return;onChange?.(option.value??option);setOpen(false);};
  return <div ref={rootRef} className={`relative ${className}`}>{label&&<span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>}<button type="button" disabled={disabled} aria-haspopup="listbox" aria-expanded={open} aria-controls={listId} onClick={()=>!disabled&&setOpen((current)=>!current)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-left text-sm text-slate-700 outline-none transition focus:border-amber-400 focus:ring-4 focus:ring-amber-100 disabled:cursor-not-allowed disabled:opacity-60"><span className={selected?'font-medium text-slate-800':'text-slate-400'}>{selected?.label??selected??placeholder}</span><ChevronDown size={17} className={`shrink-0 transition ${open?'rotate-180':''}`}/></button>{open&&<div id={listId} role="listbox" className="absolute z-50 mt-2 max-h-72 w-full overflow-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">{options.map((option)=>{const optionValue=option.value??option;const optionLabel=option.label??option;const active=optionValue===value;return <button key={String(optionValue)} type="button" role="option" aria-selected={active} onClick={()=>choose(option)} className={`flex w-full items-center justify-between gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${active?'bg-amber-50 font-semibold text-slate-950':'text-slate-600 hover:bg-slate-50'}`}><span>{optionLabel}</span>{active&&<Check size={16} className="text-amber-600"/>}</button>})}</div>}</div>;
}
