import { BriefcaseBusiness,Check,Clock3,Rocket,Sparkles,Star,Zap } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { apiRequest } from '../../lib/api.js';

const icons={'candidate-profile-boost':Sparkles,'job-featured':Star,'job-search-boost':Rocket,'job-urgent':Zap};
export default function PromotionsPage({role}){const [products,setProducts]=useState(null);const [promotions,setPromotions]=useState([]);const [jobs,setJobs]=useState([]);const [selection,setSelection]=useState({product:'',days:0,targetId:''});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const load=async()=>{const [catalogue,history,jobsResponse]=await Promise.all([apiRequest(`/${role}/promotions/catalogue`),apiRequest(`/${role}/promotions`),role==='recruiter'?apiRequest('/recruiter/jobs'):Promise.resolve({jobs:[]})]);setProducts(catalogue.products||[]);setPromotions(history.promotions||[]);setJobs((jobsResponse.jobs||[]).filter((job)=>['published','reviewing'].includes(job.status)));};
  useEffect(()=>{let cancelled=false;Promise.all([apiRequest(`/${role}/promotions/catalogue`),apiRequest(`/${role}/promotions`),role==='recruiter'?apiRequest('/recruiter/jobs'):Promise.resolve({jobs:[]})]).then(([catalogue,history,jobsResponse])=>{if(!cancelled){setProducts(catalogue.products||[]);setPromotions(history.promotions||[]);setJobs((jobsResponse.jobs||[]).filter((job)=>['published','reviewing'].includes(job.status)));}}).catch((error)=>!cancelled&&setMessage(error.message));return()=>{cancelled=true;};},[role]);
  const selected=useMemo(()=>products?.find((item)=>item.id===selection.product),[products,selection.product]);const choose=(product,option)=>setSelection({product:product.id,days:option.days,targetId:role==='candidate'?'':selection.targetId});
  const create=async()=>{if(!selection.product)return;if(role==='recruiter'&&!selection.targetId){setMessage('Select the job you want to promote.');return;}setBusy(true);setMessage('');try{const response=await apiRequest(`/${role}/promotions`,{method:'POST',body:JSON.stringify({product:selection.product,durationDays:selection.days,targetId:selection.targetId})});setMessage(response.message);setSelection({product:'',days:0,targetId:''});await load();}catch(error){setMessage(error.message);}finally{setBusy(false);}};
  if(!products)return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">{message||'Loading promotions…'}</div>;
  return <section className="space-y-6"><div className="overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#F3E8A2]">RB Promote</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{role==='candidate'?'Stand out when recruiters search.':'Put priority roles in front of more candidates.'}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{role==='candidate'?'Profile Boost is designed to increase your visibility to recruiters while your profile remains open to work.':'Promotions give active jobs additional visibility. Sponsored placements will always be clearly labelled to candidates.'}</p></div></div>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
  <div className="grid gap-4 lg:grid-cols-3">{products.map((product)=>{const Icon=icons[product.id]||Sparkles;return <article key={product.id} className={`rounded-[1.6rem] border bg-white p-5 shadow-sm transition ${selection.product===product.id?'border-amber-400 ring-4 ring-amber-100':'border-slate-200'}`}><div className="grid size-11 place-items-center rounded-xl bg-amber-50 text-amber-700"><Icon size={21}/></div><h2 className="mt-4 text-xl font-semibold text-slate-950">{product.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{product.description}</p><div className="mt-5 space-y-2">{product.options.map((option)=><button type="button" key={option.days} onClick={()=>choose(product,option)} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-left text-sm transition ${selection.product===product.id&&selection.days===option.days?'border-slate-950 bg-slate-950 text-white':'border-slate-200 hover:border-amber-300'}`}><span>{option.days} days</span><strong>₹{option.amount.toLocaleString('en-IN')}</strong></button>)}</div></article>})}</div>
  {selected&&<div className="rounded-[1.6rem] border border-amber-200 bg-[#F3E8A2]/25 p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-800">Purchase summary</p><h3 className="mt-2 text-xl font-semibold text-slate-950">{selected.name} · {selection.days} days</h3>{role==='recruiter'&&<label className="mt-4 block max-w-xl text-sm font-semibold text-slate-700">Job to promote<select value={selection.targetId} onChange={(event)=>setSelection((current)=>({...current,targetId:event.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-amber-400"><option value="">Select an active job</option>{jobs.map((job)=><option key={job._id} value={job._id}>{job.title}</option>)}</select>{!jobs.length&&<span className="mt-2 block text-xs font-normal text-amber-800">You need a published or reviewing job before purchasing a job promotion.</span>}</label>}<p className="mt-3 text-xs leading-5 text-slate-500">Payment is not charged yet. This currently creates a pending promotion order; activation begins only after the payment gateway verifies payment.</p></div><button type="button" disabled={busy||(role==='recruiter'&&!jobs.length)} onClick={create} className="rounded-xl bg-[#E3A341] px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy?'Creating…':'Continue to payment'}</button></div></div>}
  <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-950">My promotions</h2><p className="mt-1 text-sm text-slate-500">Orders and active promotion periods are tracked here.</p></div><BriefcaseBusiness size={21} className="text-slate-400"/></div><div className="mt-5 space-y-3">{promotions.length?promotions.map((promotion)=><div key={promotion._id} className="flex flex-col gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-slate-900">{products.find((item)=>item.id===promotion.product)?.name||promotion.product}</strong><Status value={promotion.status}/></div><p className="mt-1 text-xs text-slate-500">{promotion.durationDays} days · ₹{promotion.amount.toLocaleString('en-IN')} · created {new Date(promotion.createdAt).toLocaleDateString()}</p></div><div className="text-xs text-slate-500">{promotion.status==='active'&&promotion.endsAt?<><Clock3 size={14} className="mr-1 inline"/>Ends {new Date(promotion.endsAt).toLocaleDateString()}</>:promotion.status==='pending'?'Awaiting payment':'Promotion history'}</div></div>):<div className="rounded-2xl border border-dashed border-slate-300 p-7 text-center text-sm text-slate-400">No promotions purchased yet.</div>}</div></div></section>;
}
function Status({value}){const active=value==='active';return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${active?'bg-emerald-100 text-emerald-700':value==='pending'?'bg-amber-100 text-amber-700':'bg-slate-200 text-slate-600'}`}>{active&&<Check size={12}/>} {value}</span>}
