import { Bell, CheckCheck, ExternalLink } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../lib/api.js';
import { getSocket } from '../../lib/socket.js';

export default function WorkspaceNotificationsPage({role}){
  const [items,setItems]=useState(null);const [unread,setUnread]=useState(0);const [message,setMessage]=useState('');const [busy,setBusy]=useState('');
  const endpoint=`/${role}/notifications`;
  const load=useCallback(async()=>{try{const r=await apiRequest(endpoint);setItems(r.notifications||[]);setUnread(r.unreadCount||0);setMessage('');}catch(e){setMessage(e.message);}},[endpoint]);
  useEffect(()=>{let cancelled=false;apiRequest(endpoint).then((r)=>{if(!cancelled){setItems(r.notifications||[]);setUnread(r.unreadCount||0);}}).catch((e)=>!cancelled&&setMessage(e.message));const socket=getSocket();socket.connect();const refresh=()=>{if(!cancelled)load();};socket.on('notification:updated',refresh);return()=>{cancelled=true;socket.off('notification:updated',refresh);};},[endpoint,load]);
  const markRead=async(item)=>{if(item.readAt||busy)return;setBusy(item._id);try{await apiRequest(`${endpoint}/${item._id}/read`,{method:'PATCH'});await load();}catch(e){setMessage(e.message);}finally{setBusy('');}};
  const markAll=async()=>{if(!unread||busy)return;setBusy('all');try{const r=await apiRequest(`${endpoint}/read-all`,{method:'PATCH'});setMessage(r.message);await load();}catch(e){setMessage(e.message);}finally{setBusy('');}};
  return <section className="space-y-6"><div className="rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#F3E8A2]">Activity center</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Notifications</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Application updates, new applicants, job alerts and workspace activity appear here as they happen.</p></div><button type="button" onClick={markAll} disabled={!unread||Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50"><CheckCheck size={17}/>{busy==='all'?'Marking…':'Mark all read'}</button></div></div>{message&&<div role="status" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}<div className="rounded-[1.7rem] border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-semibold text-slate-950">Recent activity</h3><p className="mt-1 text-xs text-slate-500">{unread} unread notification{unread===1?'':'s'}</p></div></div>{!items?<State text="Loading notifications…"/>:!items.length?<State text="No notifications yet. New activity will appear here."/>:<div className="divide-y divide-slate-100">{items.map((item)=><article key={item._id} className={`flex gap-4 p-5 ${item.readAt?'bg-white':'bg-[#F3E8A2]/20'}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.readAt?'bg-slate-100 text-slate-500':'bg-[#879E83] text-white'}`}><Bell size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold text-slate-950">{item.title}</h4>{!item.readAt&&<span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-indigo-700">New</span>}</div><p className="mt-1 text-sm leading-6 text-slate-600">{item.message}</p><p className="mt-2 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-2">{item.link&&<Link to={item.link} onClick={()=>markRead(item)} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Open <ExternalLink size={13}/></Link>}{!item.readAt&&<button type="button" disabled={Boolean(busy)} onClick={()=>markRead(item)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 disabled:opacity-50">{busy===item._id?'Marking…':'Mark read'}</button>}</div></div></article>)}</div>}</div></section>;
}
function State({text}){return <div className="p-10 text-center text-sm text-slate-500">{text}</div>}
